### ISSUE TITLE
Looking to completely disable user controls 

### ISSUE THREAD

**Issue by jonrrivera** [CookPete/react-player#1010]
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

#### Current Behavior

controls showing on mouseover

#### Expected Behavior

I want to find a way to completely disable controls. Looking to have videos playing in the background 

#### Steps to Reproduce

1. disabled 
1. controls = 'false'
1.

#### Environment
- URL attempting to play: https://cdn.omarapollo.com/omap/video/BG-VIDEO-DESKTOP_afdkrb_ltbjh1.mp4
- Browser: chrome
- Operating system: iOs

#### Other Information

<img width="640" alt="Screen Shot 2020-09-08 at 2 17 10 PM" src="https://user-images.githubusercontent.com/18686388/92528707-35336c00-f1f7-11ea-8282-886997d99847.png">

**Comment by jonrrivera** [comment]
interesting. Controls are disabled by default. When controls = ' false' they still show. I fixed the issue by not declaring nothing

**Comment by CookPete** [comment]
There is a difference between `controls='false'` and `controls={false}`. Using `'false'` with quotes is passing the string `"false"` as the prop, which will evaluate to a `true` boolean and show the controls. Using `controls={false}` with curly brackets passes a `false` boolean to the prop, which is correct. The default is `false` which is why removing the line completely has fixed it.

**Comment by jonrrivera** [comment]
is it possible to customize player? something assigning my own custom play, pause, and fullscreen button ?

**Comment by CookPete** [comment]
See https://github.com/CookPete/react-player/issues/174#issuecomment-293329909
