### ISSUE TITLE
swipe doesn't work with div which contains a react-player

### ISSUE THREAD

**Issue by ShevkoTatsiana** [cookpete/react-player#1020]
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

#### Current Behavior
I need to use react-player inside a carousel. This carousel should support a swipe gesture for the mobile version. I try to use react-bootstrap carousel and swiper/react. In both cases slides which contain react-player element don't react on swipe gesture.

#### Expected Behavior
I can use swipe to switch slides with react-player

#### Steps to Reproduce
1. To add carousel element(f.e. swiper/react)
2. To insert element with react player into the slide item
3. Try to swipe carousel items in mobile version

#### Environment
- Browser: all
- Operating system: all

**Comment by CookPete** [comment]
If you don't need click events on the player, you could use `pointer-events: none` on the player div to prevent any touch events from being swallowed by the player API.

**Comment by ShevkoTatsiana** [comment]
but in this case will controls still work?

**Comment by CookPete** [comment]
Controls won't work. If you want to use controls there's nothing we can really do. Touch and swipe events will likely be consumed by whatever player API you are using (you didn't add an example URL so I don't know what API is being used).

It's like the Youtube player API swallowing key presses to play/pause the video when you hit spacebar. The player API stops the event from propagating to prevent the page from scrolling down.

**Comment by ShevkoTatsiana** [comment]
I got it, thank you for your answer

**Comment by DenyVeyten** [comment]
@CookPete Would it possible to handle swipe event at the capturing phase as the main intention of a user during swiping over the screen with video is to stroll page / swipe container rather than interact with video.
I understand that in some cases swipe may be true intention to interact with exact slide content, but at least it may be a developer's option to choose, how to interact with content that they pass inside.

**Comment by CookPete** [comment]
It may be possible, but I don’t know how off the top of my head. I also unfortunately don't have the means or the time to try and solve this problem.

There may be a hacky solution using an overlay div that somehow proxies any clicks/taps to the video behind, but handles swipe gestures? The problem is that every player API is different, and handles interactions differently. You may be able to handle swipe gestures with a file path URL, as that just renders a `<video>` that you could add event listeners too. The same thing isn't as easy when an iframe is used (as with most other players).

**Comment by DenyVeyten** [comment]
@CookPete Yeah, this may be a good workaround with overlay div. Thanks!
