### ISSUE TITLE
Play video with light on IPhone/IPad

### ISSUE THREAD

**Issue by denny7** [cookpete/react-player#1050]
I use the following method attached to 

onClick: 

```
  handlePlayPause = () => {

        if (!this.state.isStarted && this.props.hasLight) {

            this.setState({
                isLoadingVideo: true,
                playing: true
            }, () => this.player.handleClickPreview());

        } else {

            this.setState(prevState => ({playing: !prevState.playing}));

        }

 };
```

onReady:

```
  handleReady = () => this.setState({isLoadingVideo: false});
```

onStart:

```
  handleStart = () => this.setState({isStarted: true});
```

What I'm trying to do is to remove thumbnail(light) and play the video when user clicks the thumbnail. Everything works well on Mac or android, but not same on IPhone/IPad. When I click the thumbnail, it disappears, but video doesn't start. What is more, when I click on play, video doesn't start again. Video starts after second click on play button.

#### Expected Behavior
Play video after click on thumbnail.

**Comment by maurice-mf** [comment]
Running into into the same problem too, with using Light.

Can try it with the official demo actually:  https://cookpete.com/react-player/ 

1. load it on your phone
2. Pick Vimeo/Youtube
3. Pick Light mode
4. See player demo update with cover image, then tap image
5. Player loads, but pauses on 1st frame

I suspect that the light mode tries to embed in our videos with autoplay. And that just doesn't play. Unless it's muted. Which is weird, since I thought the preview was a way to trick the player to play unmuted due to user interaction.

There could also be some complex user-behaviour tracking on the phone (IOS). Like what was the user last setting on a video. Muted? Was playing? /shrug

I tried this with Youtube and Vimeo

**Comment by cookpete** [comment]
>I thought the preview was a way to trick the player to play unmuted due to user interaction.

Light mode is just a way to defer loading the full player API until the user wants to watch the video. It actually causes more problems on mobile than it solves. See https://github.com/cookpete/react-player/issues/1034 for more.
