### ISSUE TITLE
onMuted callback

### ISSUE THREAD

**Issue by Jacob-CT** [cookpete/react-player#1076]
I've looked at a few of the issues that address this to some extent but I'm confused why there isn't an actual callback function track whether video is muted or unmuted?

#### Current Behavior
I've seen the `onProgress` solution but that also continuously updates and causes the `dataLayer` to push every time the `onProgress` is updated... not really ideal if you just want to know when the unmutes or mutes.

@cookpete I believe your example to a listener demonstrates this https://jsfiddle.net/nxkfue56/ 

#### Expected(Liked) Behavior
It would be ideal if we had simply a callback function for mute similar to the `onPlay` and `onPause`

**Comment by cookpete** [comment]
ReactPlayer can only support what the player APIs support. The only player API I can find that has a muted event is Wistia. There is no value in adding a callback prop only supported by one type of player. If you are playing Wistia videos and you want to know when the player is muted, you can just add a listener yourself using `getInternalPlayer`. For all other video types we can't support `onMuted` simply because the players do not tell us when they are muted or unmuted.

Not even `<video>` elements have a muted event (you can listen for `volumechange` events but obviously that triggers on every volume change too).
