### ISSUE TITLE
Cannot set video width or height

### ISSUE THREAD

**Issue by desa** [cookpete/react-player#1086]
## Current Behavior
When I provide a value other than `auto` or `100%`  for `width`/`height` to `ReactPlayer` it is ignored.

#### Expected Behavior
The style I provide to react player should be respected.

#### Steps to Reproduce
https://github.com/cookpete/react-player/blob/c9421f718f71be46172b24e19d64a9d4aeaa500e/src/players/FilePlayer.js#L329-L332

should  be
```
    const style = {
      width: width || '100%',
      height: height || '100%'
    }
```

**Comment by MattAgn** [comment]
Have you tried using the width and height props?

**Comment by cookpete** [comment]
Individual players use `100%` width and height in order to fill the [top level wrapper](https://github.com/cookpete/react-player/blob/d47aa03ffc0902977038401b0604d87a7fe712f1/src/ReactPlayer.js#L165-L175), which gets given the `width` and `height` that you pass as props.

For example:

```js
<ReactPlayer width='640px' height='480px' />
```

results in something like:

```js
<div style={{ width: '640px', height: '480px' }}>
  <video style={{ width: '100%', height: '100%' }} /> // 100% here to fill the wrapper
</div>
```
