### ISSUE TITLE
Fullscreen option does not work for Iphones with OS version 14.2 or higher

### ISSUE THREAD

**Issue by spoko** [cookpete/react-player#1119]
#### Current Behavior
When test the Demo page (https://cookpete.com/react-player/) with an iPhone version 14.2 or higher the fullscreen option doesn`t seem to work. Then if you hit pause and then play the video (MP4) starts playing at the full screen only i.e. the user is not able to choose whether or not the video to be played on full screen.

#### Expected Behavior
User to be able to choose between full-screen player and not the full-screen player.

#### Steps to Reproduce
1. Open the Demo page
2. Click on MP4 video
3. Click on the Fullscreen button => nothing happens
4. Click on the pause button
5. Click on the resume button => the video starts in fullscreen mode and no way to be in non-fullscreen mode.

#### Environment
- URL attempting to play: https://cookpete.com/react-player/
- Browser: Safari
- Operating system: iOS v14.2 or higher

**Comment by cookpete** [comment]
The fullscreen button on the demo page is powered by https://github.com/sindresorhus/screenfull.js which is nothing to do with ReactPlayer and not guaranteed to work on iOS, which has it's own rules about fullscreen video.

The video only playing in fullscreen mode is simply because the demo app doesn't use the `playsinline` prop.

The need to click pause first is likely due to iOS (and other browsers) requiring a user interaction before playing media.

**Comment by Loque-** [comment]
There is a way around this by adjusting this inline value on the fly: https://developer.apple.com/documentation/webkitjs/htmlvideoelement/1631913-webkitpresentationmode

something like;

```
const HTML5VideoElement = videoRef.current.getInternalPlayer();

if (
    HTML5VideoElement.webkitSupportsPresentationMode &&
    typeof HTML5VideoElement.webkitSetPresentationMode === 'function'
) {
    HTML5VideoElement.webkitSetPresentationMode(
        HTML5VideoElement.webkitPresentationMode === 'fullscreen'
            ? 'inline'
            : 'fullscreen'
    );
}
```
