### ISSUE TITLE
react-player build with react-loadable

### ISSUE THREAD

**Issue by tomnyson** [cookpete/react-player#1120]
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

#### Current Behavior

react-player can't use with lazy load component
#### Steps to Reproduce

1. add react-player
1.
![image](https://user-images.githubusercontent.com/10257765/103530246-a808d700-4eb9-11eb-997d-add8d79a4200.png)
![image](https://user-images.githubusercontent.com/10257765/103530276-b2c36c00-4eb9-11eb-9191-2680b312dee9.png)
![image](https://user-images.githubusercontent.com/10257765/103530300-bc4cd400-4eb9-11eb-865c-d7297a486422.png)

1.

#### Environment
- URL attempting to play: 
- Browser: 
- Operating system: 
- jsFiddle example: https://jsfiddle.net/sv5x3ug1

**Comment by cookpete** [comment]
Your error log mentions "the above error". What is the error above that log?

**Comment by GhyslainBruno** [comment]
Hi, 

I'm having the exact same issue since I upgraded a lot of the library I used, and changed my class component into a functional one : 

![image](https://user-images.githubusercontent.com/22811607/119672088-97da9f80-be3a-11eb-91df-272c8776f595.png)

I don't really know what is happening there, no way to use ReactPlayer for me right now :-(

**Comment by naeluh** [comment]
I can confirm I am seeing this as well in Gatsby v2 and react 17.0.2 with react-player 2.9.0 and @loadable/component 5.15.0 thanks !
