### ISSUE TITLE
Player does not render unless a url is given

### ISSUE THREAD

**Issue by Nishant-Pall** [cookpete/react-player#1172]
I have included the react-player into my application, the procedure is that when I click the button, an API call is made and I get the URL back which I pass in as props to the player component. But the issue is that before I click the button to make the call, the space where the player should be is completely empty as if there's nothing there. It only pops up when the API call is completed.

This is how I use the component.

```
import React, { Component } from 'react'
import ReactPlayer from "react-player"

class Videoplayer extends Component {
    render() {
        const { videoUrl } = this.props
        // console.log(videoUrl);
        return (
            <div>
                <ReactPlayer
                    url={videoUrl}
                    height="300px"
                    width="500px"
                    controls={true}
                />
            </div>
        )
    }
}

export default Videoplayer

```

I would really appreciate your help here,
Thank you

**Comment by walidvb** [comment]
I'm not sure what your issue is.

There is a lag between the moment the iframe is added to the DOM, and it loads. That delay is due to loading the iframe's content itself(the youtube embed).
I think this library exposes an `onReady` or `onLoad` hook, so you could use that to only display at that moment maybe?

If you'd like not to render anything until the url is here, add a `if(!videoUrl){ return null }`
