### ISSUE TITLE
Index in Playlist URLs is being ignored

### ISSUE THREAD

**Issue by TheManFromEarth1** [cookpete/react-player#1178]
Set e.g. this URL with index=8:
https://www.youtube.com/watch?v=tvTRZJ-4EyI&list=PLlrk7Psha6E9SAfeFJTJHkVJjoax4MRpt&index=8

In the browser, "Kendrick Lamar - HUMBLE." opens as a video.
In react-player, it always loads the first video of the playlist with index 1.

Something else I notice:
1) If I set light={true}, the cover-image is correct before you click play.

Using: 
NextJS v10.0.4, 
React v17,
react-player 2.9.0

**Comment by TheManFromEarth1** [comment]
Workaround:

Set the index additionally under config

config={{
                youtube: {
                  playerVars: { index: 8 }
 }}}

**Comment by cookpete** [comment]
ReactPlayer wasn't really built to support playlists. It’s a nice feature because it was easy to add, but is not fully supported.

Updating the index in `config` won’t work because `playerVars` is only used when instantiating the player. Changing `playerVars` after the player is loaded will do nothing. Further to this, the config is memoized and only updates when the `url` changes (see https://github.com/cookpete/react-player/issues/1162#issuecomment-775503444)

You are better off using the `getInternalPlayer()` instance method to get the Youtube Player instance, then calling `playVideoAt()` as detailed here: https://developers.google.com/youtube/iframe_api_reference#playing-a-video-in-a-playlist

**Comment by gyurkoz** [comment]
For whos need a quick solution without code change, downgrading React Player to ^2.7.2 can solves this issue.

**Comment by walidvb** [comment]
adding a reference to #1183

**Comment by spereira2017** [comment]
Is possible to remove list param from URL to play desired video.

Example:

  const newUrl = new URL(item.resource_url);
  const urlSearchObj = new URLSearchParams(newUrl.search);
  urlSearchObj.delete('list');

  const url = `${newUrl.origin}${newUrl.pathname}?${urlSearchObj.toString()}`;
