### ISSUE TITLE
progressInterval for Vimeo sources can't be set below 250ms?

### ISSUE THREAD

**Issue by jhrtn** [cookpete/react-player#1185]
#### Current Behavior
When playing from a Vimeo URL, a callback called from `onProgress` is called a maximum of once every 250ms, no matter how low the `progressInterval` is set.

#### Expected Behavior
I've had the `progressInterval` set to 20ms with local files, streamed files and YouTube URLs with no issues. Noticed this issue when using a Vimeo URL for the first time. I use the onProgress function to draw a custom progress bar so it now looks very choppy for Vimeo URLs.

#### Steps to Reproduce
1. Play a URL from Vimeo
2. Set the progressInterval below 250
3. onProgress callback will be called sporadically, averaging out at around 250ms

#### Environment
- URL attempting to play: Any Vimeo URL, e.g. https://vimeo.com/22439234
- Browser: Seeing the same behaviour in Chrome, Firefox and Safari
- Operating system: MacOS
- jsFiddle example: https://jsfiddle.net/d2bwez01/10/

**Comment by gatesyp** [comment]
Have you found any further insight on this? 

Seems like might be related to https://github.com/cookpete/react-player/issues/1206 . I am seeing the same problem happening on the Twitch player. 

The demo Vimeo video seems fine: https://cookpete.com/react-player/ (select 'vimeo test') 

This may be a limitation of the Vimeo player , instead of react-player. (may be same situation for issue 1206)

**Comment by jhrtn** [comment]
Yeah looks like it's a limitation of the vimeo.js player, from their [docs](https://github.com/vimeo/player.js/#timeupdate):
![Screenshot 2021-06-07 at 15 49 41](https://user-images.githubusercontent.com/17256474/121038173-fba08900-c7a7-11eb-8753-79a88dfe5b00.png)
 
Not sure there's anything for react-player to do here, perhaps a mention in the docs to state that the minimum possible progressInterval may vary depending on what player is being used under the hood
