### ISSUE TITLE
Some videos not working in safari on ios 15 version.

### ISSUE THREAD

**Issue by You-J** [cookpete/react-player#1344]
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

#### Current Behavior
Some videos not working on ios 15 safari. Not all videos are not working.
It doesn't work only in certain locations. However, pure HTML5 video tags work.

(The control bar moves!)

_Exactly the same tag I am using. The only difference is the video name._
```typescript
<ReactPlayer
  url={require("public/videos/video.mp4")}
  loop
  playing
  muted
  playsinline
  config={{
    file: {
      attributes: {
        preload: "auto",
      },
    },
  }}
/>
```

#### Expected Behavior
It should work fine on ios safari with no video stuttering or screen freezes.

#### Steps to Reproduce
1. That's what I posted above.

#### Environment
ios 15.1, 15.2 mobile safari

**Comment by boulinb** [comment]
Hi!

I've had a very similar problem since the iOS 15 update.
My problem is quite different, I have to process base64 (representing mp4) and display it in a player :

- First I transform the base64 in an array of bytes and return it from the function in Blob
- Then I create a local URL with the Blob and I use it as the url of React-Player

base64 to Blob function : 

```
const b64toBlob = (b64Data: string, contentType = "", sliceSize = 512) => {
  const byteCharacters = atob(b64Data);
  const byteArrays = [];

  for (let offset = 0; offset < byteCharacters.length; offset += sliceSize) {
    const slice = byteCharacters.slice(offset, offset + sliceSize);

    const byteNumbers = new Array(slice.length);
    for (let i = 0; i < slice.length; i++) {
      byteNumbers[i] = slice.charCodeAt(i);
    }

    const byteArray = new Uint8Array(byteNumbers);
    byteArrays.push(byteArray);
  }

  return new Blob(byteArrays, { type: contentType });
};
```

Usage : 

```
 const blob = b64toBlob("MYBASE64...", "video/mp4");
 const blobUrl = URL.createObjectURL(blob); // React-Player url
```

Maybe you can try to turn your local file into a Blob and create a local URL like I do with base64 ; A lot of extra operations but this is the only solution I found at the moment 👀

I hope this will be useful for you!
