### ISSUE TITLE
Private Vimeo videos missing preview when using 'light'

### ISSUE THREAD

**Issue by TheStu** [cookpete/react-player#1345]
#### Current Behavior
When loading private vimeo videos with `light` property, the preview image is just a blank blue rectangle. Previews for public vimeo videos work as expected, and clicking on the blue rectangle of the private vimeo does load the player and video as expected, but obviously it would be nice if the preview image also displayed, instead of just a blue rectangle.

Is a blue rectangle for a preview image on private vimeo videos the expected behavior when using `light`, or am I doing something wrong?

#### Environment
latest react-player

**Comment by srtena** [comment]
Check this URL: https://vimeo.com/api/oembed.json?url={{your_vimeo_url}}
And then check this one: https://noembed.com/embed?url={{your_vimeo_url}}

If the first one (Vimeo) returns a 404, the problem is indeed your video, as the embedding information can't be retrieved publicly. If the first one does return the info but the second one returns 404, then you're having the same issue as me, which I feel it's a cache issue on noembed side: https://github.com/leedo/noembed/issues/120

**Comment by TheStu** [comment]
@srtena both URLs work, so seems like it's not a problem with retrieving meta data. thanks for the tip!

**Comment by cookpete** [comment]
I’m not too surprised that thumbnails don’t work for private videos.

You can fetch a thumbnail URL any way you like and pass it as the `light` prop.

It’s worth noting that ReactPlayer lets you pass your own thumbnail URL, fetched from wherever you like, as the `light` prop.

```jsx
<ReactPlayer
  url={myVimeoUrl}
  light={myFetchedImageUrl}
/>
```

**Comment by mbogunovic** [comment]
Guess this is still active, but the issue is more of a behavior than an issue:
1. When I create a video and try to fetch the thumbnail, react player queries for thumbnail via oembed.com link
2. Tried configuring the oembed.com link to accept different url (player.vimeo.com/video/id to vimeo.com/id). This didn't quite work, why? Because when the thumbnail is fetched it is probably still not generated and I get 404 which is cached, so no luck with that
3. Solutions mentioned above is just breaking the cache or using different approach to avoid solution
4. What you can do is try my fix if nothing helps:
`const Thumbnail = (prop: {videoUrl: string}) => {
    const [thumbnailurl, setThumbnailUrl] = useState<string>();

    fetch("https://vimeo.com/api/oembed.json?url=" + prop.videoUrl)
      .then(x => x.json())
      .then(x =>  setThumbnailUrl(x.thumbnail_url))
    
    return <img className="absolute top-0 left-0 h-full w-full cursor-pointer" src={ thumbnailurl } />;
  }`
  
And insert this component inside the light property of ReactPlayer. This will use vimeo's api to fetch the thumbnail which should work in any case.

Cheers
