### ISSUE TITLE
React hooks - Multiples sections (rows) videos playing all videos on hover (onMouseEnter)

### ISSUE THREAD

**Issue by Learning-X** [cookpete/react-player#1358]
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

#### Current Behavior

I just do not know what to do anymore after searching over the web over the last few days. It's obviously a lack of experience from my side so help would be very appreciated.

I'm rendering an array of sections with react using hooks, so we can see a page with many sections that contains a video. In each section ListItem, I have a ReactPlayer video Item. When I'm hovering a section, onMouseEnter of that section only, ALL videos of every sections start playing which is not what I want.

#### Expected Behavior

I want to hover a section and start playing that video Item of that section only. Important that I want to do this on hovering the section and not the video Item.

#### Steps to Reproduce

1. So far I'm passing a function parent to child holding the state play of that video item which is a boolean for that video, but I know I should use some index and or useRef to identify where it's coming from, but kind of lost here.

#### Environment
- URL attempting to play: 
- Browser: Firefox, chrome
- Operating system: mac os

**Comment by cookpete** [comment]
It sounds like you need to store a `playing` state for each individual section, rather than one `playing` state that gets passed to every section.

Alternatively, store a `playingIndex` state at the top level, which gets updated when you hover over each section. Then in your player props you can do `playing={playingIndex === sectionIndex}` or similar.
