### ISSUE TITLE
SproutVideo Support

### ISSUE THREAD

**Issue by iDVB** [CookPete/react-player#147]
Hey @CookPete,
We've almost completed a PR for [SproutVideo](https://sproutvideo.com) support.
Just a few questions. How are you managing the npm package for this currently?
I see in the package.json that main is ` "main": "lib/ReactPlayer.js"` but lib is ignored in the gitignore.

Just thinking this out, as usually when building/working with a PR fork, I'd point my application's package.json for this module to my forked repo directly.  

Maybe I'm missing something but I think that would not work in this case?

**Comment by iDVB** [comment]
ping

**Comment by CookPete** [comment]
Hey @iDVB, the `lib` folder is where the compiled `src` files go after running `npm run build:compile`. They are in `gitignore` because there is no reason for those files to be under version control.

If you have a custom version of this repo checked out somewhere, you can use `npm run build:compile` and then [`npm link`](https://docs.npmjs.com/cli/link), and then in your application you can run `npm link react-player` to use your custom `react-player` build.

**Comment by iDVB** [comment]
@CookPete ya got that... but I think I just realized something I did not know about npm.
I was under the impression that in order to register a package in the node registry, you needed to have the built files committed to the repo you registered. I guess I figured npm was just key:value and served the files up direct from the repo. 

But after reading this, I poked around a few popular modules and sure-nuff there are many that don't. https://github.com/reactjs/react-redux 

Gonna need to read some more on module dev me things. ;)

**Comment by CookPete** [comment]
Yeah, the files committed to the repo are not necessarily the same as the files that `npm` holds for your library. `npm publish` will upload all files in your root directory (ignoring those in `.npmignore`) to the registry. The `prepublish` script will run before publishing, hence why we run our build scripts [here](https://github.com/CookPete/react-player/blob/master/package.json#L19) so that `lib` and `dist` are freshly built before publishing.

**Comment by oyeanuj** [comment]
@iDVB I was wondering if this is still on the radar? And/or if there is a branch/fork where one can play with it?

**Comment by CookPete** [comment]
Will close this off for now. @iDVB feel free to open a PR if you got somewhere with this.

**Comment by gondalsaimraza** [comment]
Hey guys.. Was the support for Sproutvideo ever added? I kind of need it for a project i'm working on but i cant find it in the docs.

Thanks

**Comment by rcbxd** [comment]
hey @gondalsaimraza I had the same problem a couple days back so I've made a [library](https://github.com/rcbxd/react-sproutvideo) that utilizes their iFrame API and turns it into a fully controllable player using React components and refs, check it out and contribute if you still need it :)
