### ISSUE TITLE
Setting fallback url in onError will throw error

### ISSUE THREAD

**Issue by dnovacik** [cookpete/react-player#1504]
#### Current Behavior

I'm using manifest files in the player and they are not always compliant so I'm trying to set backup url if an onError is triggered. But as soon as I set a new url, it wouldn't work, it would throw an error again `error: e {code: 32, message: 'No streams to play.', data: null}`

EDIT: I am using this as a validator of which file I can use later in the app to render. So the modal with video returns working url with onReady() from the ReactPlayer. If I tried to get the url from the instance passed to onReady() it would be an array and not the actual file being rendered. 

This is the code:

```
  const [currentUrl, setCurrentUrl] = useState<string>(url);

  const onError = (error: any, data: any) => {
    if (backupUrl) {
      setCurrentUrl(backupUrl);
      // setValidationState("Validating backup media file...");
    }
  };

// then later in return ()
       {
          ReactPlayer.canPlay(currentUrl) ? (
            <ReactPlayer
              url={currentUrl}
              loop={true}
              muted={true}
              controls={true}
              onError={(e, d) => onError(e, d)}
              onReady={(p) => onReady(p)} />
          ) : null
        }


```
If I try to insert the backup right away (mp4 file) it works np, also when I insert an array of both the mpd and mp4 it works correctly.

#### Expected Behavior

Setting a new url in onError would actually process and play the video correctly.

**Comment by hernandiazz9** [comment]
Hi there, I've been trying  to catch your issue.
My opinion is that if you use ReactPlayer.canPlay(currentUrl) there, you can’t  have access  to onError because it will never try to play and will not generate an error.
I think you should use ReactPlayer.canPlay(currentUrl) before the return  and map the array checking with canPlay method and fil up your state of videos.
Otherwise when you have an error you will receive it from onError and there you can change the currentURL and will work.

Hopefully it clear.

cheers
