### ISSUE TITLE
Help: Loading spinner while player is not yet ready

### ISSUE THREAD

**Issue by bk973** [cookpete/react-player#1552]
Need a way to display a loading spinner when player is not yet ready... Anybody done this before???

**Comment by inderrr** [comment]
You mean while the player is buffering?

**Comment by bk973** [comment]
Yes

**Comment by inderrr** [comment]
Created this [sandbox](https://codesandbox.io/s/bold-hodgkin-bo9qf8?file=/src/App.js).
In style.css, native html video tag's spinner has been hidden. This only works in chrome based browsers.

I'd recommend to create custom controls for the video, to support multiple browsers.

You can also hide controls using state (find commented out prop on Player Component) while video is buffering.

**Comment by inderrr** [comment]
Created this [sandbox](https://codesandbox.io/s/bold-hodgkin-bo9qf8?file=/src/App.js).
In `style.css`, native html video tag's spinner has been hidden. This only works in chrome based browsers.

I'd recommend to create custom controls for the video instead of targeting only the spinner.

You can also hide controls using buffering state (find commented out prop on Player Component).

**Comment by bk973** [comment]
Thank you so much, this was helpful
