### ISSUE TITLE
What is the difference of using lazy player vs. using the light prop to true?

### ISSUE THREAD

**Issue by PrimozRome** [cookpete/react-player#1554]
What exactly is the difference of using lazy loaded player `react-player/lazy` vs using light prop `light={true}`?

**Comment by luwes** [comment]
- `light={true}` is about lazy loading the 3rd party players, some players like YouTube have a big bundle size so setting this option to true will hold off on loading the Youtube player iframe URL until the end user clicks on the provided preview thumbnail.
- react-player/lazy is about lazy loading the provider's API wrappers of the react-player library.
  see https://github.com/cookpete/react-player/blob/264cb10767be6f7f2ed724f33b9d3723553ca744/src/players/index.js#L10-L10
  since you might only use Youtube, Vimeo and File it makes less sense to also load the API wrappers for Wistia, Vidyard, Twitch, etc. This will reduce your main bundle but it will load the provider modules lazily when used.
