### ISSUE TITLE
Safari issue | Double play icon coming | when light url is added in the added | Poster over Video

### ISSUE THREAD

**Issue by akashgaur-kiwi** [cookpete/react-player#1676]
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

#### Current Behavior
The video is not playing on the first click as a user needs to click the play button 2 times(Whenever we add the light props in the light player)
- 

#### Expected Behavior
The video should play on a single click when the play icon is clicked.

export default function App() {
  // Collection of urls

  const playerRef = React.useRef(null);

  return (
    <div className="App">
      {/* Video Player */}
      <ReactPlayer
        // Light Mode
        light={
          "https://fastly.picsum.photos/id/468/200/300.jpg?hmac=_y9LVzJfrmELvOun_dpNOKoPajv8_vT3t3IPS6Jbhk4"
        }
        // Ref for ReactPlayer
        ref={playerRef}
        controls={true}
        // Current videos url
        url={
          "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4"
        }
      />
    </div>
  );
}

SandBox URL - https://codesandbox.io/s/react-player-light-mode-forked-4llpmd

<iframe src="https://codesandbox.io/embed/react-player-light-mode-forked-4llpmd?fontsize=14&hidenavigation=1&theme=dark"
     style="width:100%; height:500px; border:0; border-radius: 4px; overflow:hidden;"
     title="React-Player Light Mode (forked)"
     allow="accelerometer; ambient-light-sensor; camera; encrypted-media; geolocation; gyroscope; hid; microphone; midi; payment; usb; vr; xr-spatial-tracking"
     sandbox="allow-forms allow-modals allow-popups allow-presentation allow-same-origin allow-scripts"
   ></iframe>

#### Environment
- URL attempting to play: 
- Browser:  Safari Version 16.6 (18615.3.12.11.2)
- Operating system: MAC OS

**Comment by luwes** [comment]
related https://github.com/cookpete/react-player/issues/1488

it looks like with light mode you have to set `muted` to true and `playing` to true so the video autoplays when clicking the play icon.

this is because in most browsers now starting video playback with sound requires a user gesture.

since in light mode the Javascript of the player is not loaded yet, the click on the first play icon can't forward the user gesture to the player right away. because the player first need to load the JS which is async.

here's the fixed example:
https://codesandbox.io/s/react-player-light-mode-forked-q5p845?file=/src/App.js

alternative:

if you like a user click to play the video with sound then you have to disable light mode.
