### ISSUE TITLE
Specify when to begin loading video and get loaded percentage

### ISSUE THREAD

**Issue by DVassilev** [CookPete/react-player#168]
Is it possible to manually specify when the video beings loading? In addition, how can I get the loaded amount of the video?

Thanks,
Daniel

**Comment by oyeanuj** [comment]
@DVassilev I think you want to pass a callback function to the `onProgress` prop. It updates with an object containing two fractions - `loaded`, and `played`. That should allow you to determine both the things you need.

Additionally, take a look at `onReady` callback which you might also find useful.

**Comment by DVassilev** [comment]
@oyeanuj thanks for onProgress, didn't realise it also did amount loaded. As for onReady, that would just notify me when it's ready. I'd like to specifically say when the video should start loading (ie. on page load, on play etc.). I noticed <video> has a property 'preload' which is currently set to auto and has no option to change it. If there isn't an option then I'll submit a PR for it.

**Comment by CookPete** [comment]
@DVassilev The `preload` prop is a special behaviour only for youtube and vimeo players, in order to fix an [old bug](https://github.com/CookPete/react-player/issues/7). 

When playing files, however, `video` elements can indeed take a `preload` attribute, which indicates when to start loading files. This is more of a hint to browsers though, rather than something that they strictly enforce.

You can set the `preload` attribute to whatever you like if you are playing files by using `fileConfig.attributes`:

```js
<ReactPlayer
  playing
  url='file.mp4'
  fileConfig={{ attributes: { preload: 'none' }}}
/>
```

Beyond this, there is no way to control when a browser starts loading a video. Each browser (especially mobile browsers) will have different behaviours and media loading policies.

More info on the `preload` attribute [here](https://developer.mozilla.org/en/docs/Web/HTML/Element/video#attr-preload)

**Comment by DVassilev** [comment]
Thank you @CookPete
