### ISSUE TITLE
Soundcloud fails to loop.

### ISSUE THREAD

**Issue by dgbogi564** [cookpete/react-player#1686]
Soundcloud embeds fail to loop as implemented in the [demo website](https://cookpete.com/react-player/).

**Comment by luwes** [comment]
this is a limitation of the Soundcloud player because it goes to and end screen.

I recommend listening to the onProgress event and comparing the current time with the duration and set the currentime to zero when it almost reaches the end. 

this is something React player will not implement as it's possible to resolve by the user.

**Comment by vincentwinkel** [comment]
The goal of react-player isnt to abstract the limitations of every supported platforms and provide a homogeneous way to play audio/video without worrying about this kind of "details"?

I also face this problem (a soundcloud song doesnt start if the tab is not active, and also doesnt fire `onEnd` event).
I actually have issues with several platforms:
- soundcloud doesnt work properly (cf this thread)
- mixcloud works half of the time (sometimes the player is not even loaded)
- file urls don't work (cf [this thread](https://github.com/cookpete/react-player/issues/1895))
- some durations (mainly for youtube based on my tests) are wrong

react-player is great, don't get me wrong, and I understand it's complex to implement, but I would expect by using it that I would not have to manually fix limitations for this or that player.
