### ISSUE TITLE
Soundcloud not playing on Chrome or Safari

### ISSUE THREAD

**Issue by dcporter44** [CookPete/react-player#170]
I've tested your demo on both Chrome and Safari on desktop and neither of them will play SoundCloud songs. There are no console errors. It just hangs indefinitely: http://cookpete.com/react-player/

All other sources work fine.

Edit: Actually I am seeing a console error. It's a 429 (Unknown) error
GET https://api.soundcloud.com/tracks/188380421/stream?client_id=e8b6f84fbcad14c301ca1355cae1dea2 429 (Unknown)

**Comment by CookPete** [comment]
A `429 Too Many Requests` happens when the soundcloud request limit is hit. I guess the library (and demo page) have become popular enough to hit the limit on the default API key I set up. The problem will disappear once the current rate limit window (24 hours) has passed, but I guess the time has come where we need to force developers to use their own SoundCloud API key.

For your own implementation (and anyone reading), use `soundcloudConfig.clientId` like so:

```js
<ReactPlayer
  url='...'
  soundcloudConfig={{
    clientId: MY_SOUNDCLOUD_CLIENT_ID
  }}
/>
```

More info:
* https://httpstatuses.com/429
* https://developers.soundcloud.com/docs/api/rate-limits
