### ISSUE TITLE
No event trigger when ReactPlayer is load

### ISSUE THREAD

**Issue by karamata** [CookPete/react-player#182]
on begin my component didn't render ReactPlayer, but after some action, it will render ReactPlayer, but no event trigger
my code is similar...

```
if ( playingYoutube ) {
	return (
		<ReactPlayer
          ref={player => { this.player = player }}
          url={this.props.videoUrl}
          width='100%'
          height='100%'
          playing={this.props.playerStatus === 'play' ? true : false}
          playbackRate={1}
          className='react-player'
          volume={this.state.volume}
          onReady={() => console.log('onReady');}
          onStart={() => console.log('onStart');}
          onPlay={() => console.log('onPlay');}
          onPause={() => console.log('onPause');}
          onBuffer={() => console.log('onBuffer');}
          onEnded={() => console.log('onEnded');}
          onError={() => console.log('onError');}
          onProgress={() => console.log('onProgress');}
          onDuration={() => console.log('onDuration');}
          />
	);
} else {
	return (
		{/* other component*/}
	)
}
```

youtube player can load, but I see no thing print on console, is this a bug of youtube iframe sdk? is there anyway to solve that problem, please help!

**Comment by meandavejustice** [comment]
Not sure if I'm seeing the same issue as above, but mine seems possibly related.

When switching the source url on the player it starts to load the new video. If you unset the current url and set it to the same url again. The load event is not called. (The usecase for this would be if the developer has a sort of queue or playlist to cycle through with the player and there are duplicate videos in the list.

**Comment by CookPete** [comment]
>If you unset the current url and set it to the same url again. The load event is not called.

What "load event" are you referring to? If you mean `onReady`, that will fire even if the previous video is the same URL as the current one. However, you must render ReactPlayer at least once with no `url` so that `stop` is called interally, otherwise nothing will happen (because as far as ReactPlayer knows, no props have changed). Without knowing how exactly you are unsetting and setting the URL, I can't be much more help.

Alternatively, you could add a check to your app's logic to compare the previous and next URL, and if they are the same, just call `seekTo(0)` instead of unsetting/setting the URL to force a fresh load?

**Comment by CookPete** [comment]
@karamata I'm not sure exactly what would cause there to be no console logs in your example. Is it possible to reproduce the problem in a jsFiddle? [This one](https://jsfiddle.net/nrj9r60g/) can get you started.

**Comment by karamata** [comment]
hi @CookPete ,
I find out reason of issue, that because some of my library, sorry I can not share my library here is override something in youtube api javascript, that just my assumption. I have fix my library and it work now, thank for your great work
