### ISSUE TITLE
jsdelivr issue

### ISSUE THREAD

**Issue by kah9509** [cookpete/react-player#1834]
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

#### Current Behavior
HLS video does not play.

#### Expected Behavior
The problem seems to be occurring because the jsdelivr CDN certificate has expired.

#### Steps to Reproduce

1.
1.
1.

#### Environment
- URL attempting to play: 
- Browser: 
- Operating system: 
- jsFiddle example: https://jsfiddle.net/sv5x3ug1

**Comment by edoko** [comment]
https://github.com/cookpete/react-player/issues/605#issuecomment-492561909

I'm having the same problem.
There are ways to temporarily replace it with another CDN.
Load the hls.js script before the react-player is loaded.
```
<script src="https://cdnjs.cloudflare.com/ajax/libs/hls.js/1.1.4/hls.min.js" />
```

If possible, I'd like to see ReactPlayer change the default CDN address, or have it built in by default.
(Although I understand from the comments in the issue above that it doesn't due to bundle size)

**Comment by kah9509** [comment]
Thank you!!!!
I'll give it a try.

**Comment by kah9509** [comment]
It works very well. thank you.

**Comment by mislavmiocevic** [comment]
If you are using Next (14) you can have:

``` //_document.tsx
import Script from 'next/script';

...
<Head>
    ...
    <Script src="https://cdnjs.cloudflare.com/ajax/libs/hls.js/1.1.4/hls.min.js" strategy="beforeInteractive" />
```
