### ISSUE TITLE
Support of dash,hls

### ISSUE THREAD

**Issue by ricking06** [CookPete/react-player#184]
Does it supports dash and hls ? anytime soon ?

**Comment by CookPete** [comment]
The player falls back to `<video>` if the `url` passed in cannot be played by any of the custom players. Any browser that supports HLS or DASH will work. Try opening [this fiddle](https://jsfiddle.net/99ee3atp/2/) in Safari to see `ReactPlayer` working with one of Apple's [example HLS streams](https://developer.apple.com/streaming/examples/).

**Comment by oyeanuj** [comment]
Hey @CookPete, so it seems that your link above works only in Safari since that comes with native support for HLS. What do you think about adding [HLS.js](https://github.com/video-dev/hls.js) or Dash.js, so that they play in all the browsers? 

[Shaka-player](https://github.com/google/shaka-player) seems to be one that is referenced at several places as incorporating both libraries.

**Comment by oyeanuj** [comment]
@CookPete To provide more context for this request, I am thinking that if we incorporate these two libraries, then that might mean that it should (theoretically) work on all browsers, which would mean a huge saving in encoding cost, since you are only encoding to one format (and not needing to deal with multiple resolutions either).

Thoughts?

**Comment by CookPete** [comment]
@oyeanuj I wasn't aware of these libraries until now but they looks like a good solution. I have integration with `hls.js` working for `.m3u8` URLs so will publish that soon after I look at supporting dash too. In the meantime, are there any other HLS file extensions to detect? I've also added a `forceHLS` config option to `fileConfig` for more ambiguous URLs.

**Comment by oyeanuj** [comment]
@CookPete Awesome, thats good to hear! For `hls`, it seems like `.m3u8` would be sufficient [according to Apple](https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/StreamingMediaGuide/HTTPStreamingArchitecture/HTTPStreamingArchitecture.html).

Will have to study MPEG-DASH more to respond for that.

**Comment by CookPete** [comment]
The [dash.js readme](https://github.com/Dash-Industry-Forum/dash.js) examples use `manifest.mpd` so I'll use `mpd` for now, and add a `forceDASH` boolean to `fileConfig`.

**Comment by CookPete** [comment]
Published in `0.18.0`

**Comment by oyeanuj** [comment]
wow, that was quick!
