### ISSUE TITLE
How I can remove the default style attributes of the element video?

### ISSUE THREAD

**Issue by TiagoSousa26** [CookPete/react-player#190]
The element `video` has by default `style` `width: 100% `, `height: 100%` and `display: block` and I want to remove the `width` because that is overriding the style defined by me.
I searched but I think that is not configurable or it is? If not, there is a clean way (or not) of removing that?

**Comment by CookPete** [comment]
The `video` element has a width of 100% in order to fill the wrapper element, the size of which is defined by the `height` and `width` props.

Manually overriding the `video` element width should not be necessary if you just use ReactPlayer's `width` prop and let `video` fill the wrapper.

If you really want to override the `video` style attribute, you could do this:

```js
<ReactPlayer
  url='file.mp4'
  fileConfig={{ style: { height: '100%', width: '720px' } }}
/>
```

**Comment by TiagoSousa26** [comment]
I really need because the video gonna be fullscreen and the style only work applied to the `video` element and that was overriding. But yeah for a "normal" use it is ok and i understand why it is on that way.

Thanks a lot and good job with this lib.

**Comment by TiagoSousa26** [comment]
And by the way I was trying now and I founded you miss to involving the style object with `attributes`.
{ attributes: { style: { height: '100%', width: '720px' } } }

**Comment by CookPete** [comment]
>And by the way I was trying now and I founded you miss to involving the style object with attributes.

My bad! Example updated.
