### ISSUE TITLE
Force refresh of source

### ISSUE THREAD

**Issue by Alladinsane** [CookPete/react-player#209]
I'm using react-player to embed an icecast stream on my webpage. Plugging the stream url into react-player works well enough, but I've encountered a slight issue. Elsewhere on my page are controls for the player that is outputting to the icecast stream(I'm using mopidy). If there is nothing playing on this player when the page is first loaded, and then something is later started up, this triggers a rerender of all my elements. I thought this would also cause the react-player component to rerender, refreshing the url, but this does not seem to be the case. Playback from the react-player is silent until I reload the page, and only then does the icecast audio come through. 

My hunch is that react-player is not being rerendered when the parent component rerenders. Is there some way to make this happen, and/or force the url to be refreshed?

**Comment by CookPete** [comment]
This sounds like more of a React problem than a ReactPlayer problem. If you are re-rendering ReactPlayer with the same `url` prop, then nothing will change (as is the nature of React). One thing you could do is add a `key` to your `<ReactPlayer>` which changes when you require a re-render.

See [example JSfiddle](https://jsfiddle.net/99ee3atp/3/).

**Comment by UPLukeet** [comment]
Hi I'm having the same issue when I give my container element a unique key it forces react to refresh/rerender all elements upon playing the video but idk why?

**Comment by jdthorpe** [comment]
I think the issue is not with react player, but with the fact that that the player is rendered with a `<video />` component that the browser manages.  In particular, when the URL is unchanged, the browser will used the cached source, even if the player is removed and added back to the React DOM.  I solved this by appending a random query parameter to the url when I want the source to be refreshed.  e.g.: 

```ts
import Player from "react-player"

const MyComponent  = (url:string, key:string) => {
   // appending the something=key query parameter forces the video source 
  // to refresh whenever the key is updated  
  return <Player url={`${url}?something=${key}`} />
}
```

Note that simply adding a key parameter to the player (e.g. `<Player key={key} url={url} />`) did **NOT** solve this issue for me.
