### ISSUE TITLE
No IE11 support because of for...of loops

### ISSUE THREAD

**Issue by tansongyang** [CookPete/react-player#239]
## Issue

Because of `for...of` loops, this component does not support IE11. (And possibly other reasons—I mention the loops because they are what caused the errors in my case). You will get an error saying that `Symbol` is undefined.

## Proposal

I see a couple of options here:

1. Make it more explicit in the docs that this is a requirement. As of this writing, the docs only mention polyfills for [Promise and fetch](https://github.com/CookPete/react-player/blob/v0.24.6/README.md#polyfills)
2. Replace the loops with something like `Array.prototype.forEach`.

It's up to you. I'd be happy to do a PR either way.

**Comment by CookPete** [comment]
From a quick test, it looks like it isn't just `Symbol` that requires a polyfill, and together with the fact that [IE is down to about 3% market share](http://gs.statcounter.com/), I'm more inclined towards suggesting using a polyfill in the readme, rather than changing the library code in an attempt to support a dying browser.

After updating the library to remove `for..of` loops I started getting a pretty useless error in IE around [this line](https://github.com/CookPete/react-player/blob/5637423522066e61f573f6d95ddaf2a3aaa58279/src/utils.js#L50):

```
Object doesn't support this action
```

Then after adding `babel-polyfill` the library seems to work, although videos were failing to play after loading. The [youtube player demo page](https://developers.google.com/youtube/youtube_player_demo) also seems to not play on IE11, which is slightly comforting.

**Comment by tansongyang** [comment]
OK. What is your preference on how to update the README? I might have some time to investigate the specific things that need polyfilling in IE11. Or we could just say "If you use IE11, you `babel-polyfill`".

**Comment by CookPete** [comment]
I think most people targeting IE11 will be using `babel-polyfill` anyway, so I've just added a generic hint to the readme. I'll add `babel-polyfill` to the demo build too.
