### ISSUE TITLE
seekTo doesn't work when called before play

### ISSUE THREAD

**Issue by rijk** [CookPete/react-player#245]
In the Vimeo player at least, calling seekTo after initializing the player has an unexpected result.

Expected result: player will skip to passed frame, while remaining paused.

Actual result: player starts playing from beginning.

**Comment by mikekellyio** [comment]
I'm seeing similar behavior with the file player using dash files.

**Comment by CookPete** [comment]
This has been half-fixed by 6ddb523f2e97ef9c03e581cc8a58908f2b36f9f8, although the `setCurrentTime` method in the vimeo player API will automatically play the video after seeking. The only way to prevent this on ReactPlayer's side would be to pause immediately after seeking, maybe using the `onSeek` prop.

Also, keep in mind that there are [many existing issue with the vimeo player and `setCurrentTime`](https://github.com/vimeo/player.js/search?q=setcurrenttime&type=Issues&utf8=%E2%9C%93).

**Comment by jp3492** [comment]
how can you pause a video onSeek?
