### ISSUE TITLE
Volume Fade

### ISSUE THREAD

**Issue by edencorbin** [CookPete/react-player#252]
Any way to fade volume? Is the best approach to create a state variable and programatically update it, perhaps with an interval/timeout? Would be a great feature.

**Comment by CookPete** [comment]
Yeah the current approach would be to programatically update the `volume` prop, but I like the idea of natively supporting volume fade.

**Comment by edencorbin** [comment]
Thanks for the reply, I'll set it up like that, and perhaps turn it into a PR if I get a chance to dig into the module code.

**Comment by CookPete** [comment]
My first attempt at this is at https://github.com/CookPete/react-player/commit/6a59c9e6c1999a0759f54eb79900e0961da88b1f on the `fade-volume` branch. It bring up an interesting problem:

We already set the `volume` via props, so fading to a certain volume means we have to either:

* Use a `volumeFade` prop to indicate that when we change the `volume` prop, we want to fade to that volume instead of jump straight to it. This is more declaritive, but possibly harder to use if you want to have normal volume controls and a volume fade at other times. This is what I have tried out in the `fade-volume` branch.
* Provide a `fadeToVolume` method on the player, that fades to a certain volume. This is much easier to use but gets into a sticky problem where the volume you fade to will not be the same as the `volume` prop you pass in. Perhaps this is ok and it is enough just to warn people that the `volume` you are passing in and the actual volume of the player may not match if you use the fade method.

**Comment by edencorbin** [comment]
Fantastic progress. I will pull the branch and test for my use case soon, at which point I will have better feedback. I think the first option is good, as you can switch off the volumeFade option whenever you want the user to have control. If you end up implementing the second option you could have a onFadeComplete method where it would be best practice to set your volume state to the fade result.

**Comment by CookPete** [comment]
>Fantastic progress. I will pull the branch and test for my use case soon, at which point I will have better feedback.

Be warned that I've implemented it on a branch with a big code refactor, so keep that in mind :)

>If you end up implementing the second option you could have a onFadeComplete method where it would be best practice to set your volume state to the fade result.

I think `onFadeComplete` is a good idea regardless.

We could always just implement both and let the developer decide which they want to use, with a warning in the readme about the caveats of each method.
