### ISSUE TITLE
Dailymotion preload always loads

### ISSUE THREAD

**Issue by SkinyMonkey** [CookPete/react-player#261]
With react-player 0.25.3

I added a {preload: true} for dailymotion in the config.
If i play a youtube url I get a dailymotion node playing in the background with this url:

"http://www.dailymotion.com/embed/video/x522udb?api=postMessage&autoplay=false&controls=false&endscreen-enable=false&id=f3d4b29cd79b23&origin=http%3A%2F%2Flocalhost%3A3000&start=0"

Sorry, I don't have time to investigate this for now

**Comment by CookPete** [comment]
So it turns out that preloading had been broken for a while. It was fixed in `0.25.3` but when the dailymotion player was added, a music video was used as the preload video. It should be a blank, silent video like http://www.dailymotion.com/video/x57icfs

Can I ask why you are using the `preload` config? It's interesting to hear about people using it and why.

**Comment by CookPete** [comment]
From the title of the issue. It sounds like you may have misunderstood what `preload` does. The idea is that it will load a silent, hidden dailymotion video in the background in order to "prime" the player, and not require browser focus when a dailymotion video loads at some point later on. "Dailymotion preload always loads" is sort of the point, even when playing a youtube video first.

Either way, the preload video has been updated in the `1.0.0` beta, so try installing that:

```bash
npm install react-player@next
```

**Comment by SkinyMonkey** [comment]
I noticed in the changelog that preloading was broken but fixed in 0.25.3 that's why i thought it would be a good idea to report this.

My title was misleading.
I understood that using preload added an element in the dom playing a silent video to prevent focus problems discussed in the issue #7  and it would not bother me if it wasn't playing a track with music at the same time as the track I play.

I read the code for 0.25.3 and noticed that it's just the BLANK_VIDEO_URL that is pointing to a track that is not silent. That's it.

I'll try 1.0.0 anyway, thanks.

**Comment by CookPete** [comment]
Yeah it's my fault for not checking the `BLANK_VIDEO_URL` when the DailyMotion player was added. Hopefully you have better luck with the `1.0.0` beta.
