### ISSUE TITLE
Multiple requests making browser unresponsive

### ISSUE THREAD

**Issue by yenduttjain** [CookPete/react-player#281]
I have added this plugin, which works great. I'm showing multiple videos. But it keeps on requesting on Youtube server and becomes un-responsive on IE or slower machine. Works OK on chrome but still too many requests. Attached are the screenshots. Suggestion / Help / Guidance is much appreciated.
![youtube-2](https://user-images.githubusercontent.com/10963773/32987934-ea0552a2-cd1e-11e7-978b-5cddd2d47025.PNG)
![youtube-1](https://user-images.githubusercontent.com/10963773/32987935-ea3ee544-cd1e-11e7-85f3-d3dae4c1ffc8.PNG)

**Comment by CookPete** [comment]
`remote.js` and `log_interaction` are just built in requests from the [youtube iframe API](https://developers.google.com/youtube/iframe_api_reference). As far as I know they cannot be prevented, apart from maybe installing an adblocker. IE becoming unresponsive is _probably_ due to the sheer amount of videos you are trying to load/play at once, and not to do with these requests.
