### ISSUE TITLE
facebook width && height config doesn't work.

### ISSUE THREAD

**Issue by hardfist** [CookPete/react-player#290]
the following is my config
`
 <ReactPlayer
          url="https://www.facebook.com/video.php?v=1242620132488813"
          width={754}
          height={504}
          playing={true}
          controls
        />
`
but the size of return video is 754x422,It seems that the size only works for container style but not for the video size

**Comment by CookPete** [comment]
As far as I can tell, Facebook will adjust the height of the player to match the aspect ratio of the video, regardless of the height of the container it is in.

You have several options:

* Use the fixed height of the video in your config: `<ReactPlayer ... height={422} />`.
  * You could also try `height="auto"` to keep the height dynamic, although I'm not certain this will work.
* Use a responsive player wrapper (see [example jsFiddle](https://jsfiddle.net/e6w3rtj1/) that uses Vimeo, but it should work with any video source).
* Wrap ReactPlayer in a div with `41px` top and bottom padding to visually center the player.
  * `41px` because `(504 - 422) / 2 = 41`
