### ISSUE TITLE
Soundcloud color config doesn't seem to work

### ISSUE THREAD

**Issue by karendelakaren** [CookPete/react-player#321]
Hi, I was trying to create a soundcloud embed with a specific button color, which according to the soundcloud api documentation should work. All of the other soundcloud config works smoothly, but for the color it just adds 'color=true' to the iframe url

`config={{
    soundcloud: {
        options: {
                color: '#00174F',
                visual: false,
                show_playcount: true,
                buying: false,
                sharing: false,
                download: false
        }
    }
}}`

**Comment by CookPete** [comment]
This looks like a bug with the soundcloud widget. You can see the function that builds the URL params in the [widget code](https://w.soundcloud.com/player/api.js) (using [jsbeautify](http://jsbeautifier.org/)):

```js
function g(n) {
  var t, e, r = [];
  for (t in n) n.hasOwnProperty(t) && (e = n[t], r.push(t + "=" + ("start_track" === t ? parseInt(e, 10) : e ? "true" : "false")));
  return r.join("&")
}
```

It checks if the option is `start_track` and sets it as an integer, but otherwise just passes in `true` or `false` strings. As a temporary fix you could fork this repo and point the soundcloud player to a custom version of the widget code with the bug fixed. The long term fix will be trying to track down the Soundcloud devs and let them know of the bug. 

The fix could be as simple as:

```js
function g(n) {
  var t, e, r = [];
  for (t in n) n.hasOwnProperty(t) && (e = n[t], r.push(t + "=" + ("color" === t ? e : ("start_track" === t ? parseInt(e, 10) : e ? "true" : "false"))));
  return r.join("&")
}
```

**Comment by CookPete** [comment]
There is a repo for the widget but it looks extremely outdated: 
https://github.com/soundcloud/Widget-JS-API

**Comment by b-b0t** [comment]
Did this get resolved?

**Comment by gilluminate** [comment]
One workaround for this is to add the color property to the url instead of the config.
```
url={`${link}?color=${playButtonColor}`}
```

**Comment by owensco** [comment]
@cookpete it looks like none of the `config` overrides are working for SoundCloud which is no surprise given the age of that widget 😅 

[Options](https://developers.soundcloud.com/docs/api/html5-widget) can be passed into the URL using @gilluminate's suggestion e.g. `?show_artwork=false&buying=false`
