### ISSUE TITLE
console errors when using component for twitch stream

### ISSUE THREAD

**Issue by pedropcruz** [CookPete/react-player#358]
Hello there,

I' m trying to put my component with url and with some options on twitch, and have this error:

![image](https://user-images.githubusercontent.com/6757946/37503015-d74453f6-28cd-11e8-9ba9-3fac0b5d8540.png)

How i can solve this? Many thanks!

**Comment by hellojere** [comment]
Same with Vimeo direct URL's. Reverting back to `1.2.1` works.

**Comment by CookPete** [comment]
@pedropcruz @hellojere What URL/props are you using to cause this error? Examples code/repos/jsFiddles are very useful.

**Comment by hellojere** [comment]
@CookPete Happens with the react-player demo too when using the following for the source:

```
https://player.vimeo.com/external/134290208.sd.mp4?s=9000cee9e39cb10a907c297ec36bcde452dfb9e5&profile_id=112
```

**Comment by pedropcruz** [comment]
@CookPete in my case just showing doing this:

```
<ReactPlayer
                        className="react-player"
                        url="https://www.twitch.tv/pedropcruz"
                        config={{
                            twitch:{
                                options:{
                                    'font-size':'small',
                                    channel: 'pedropcruz',
                                    chat: 'default',
                                    layout: 'video-and-chat',
                                    theme: 'dark',
                                    src: 'https://www.twitch.tv/pedropcruz/chat'
                                }
                            }
                        }}
                    />
```

**Comment by CookPete** [comment]
@pedropcruz your config is working correctly for me? See [jsFiddle](https://jsfiddle.net/gjevzs6m/). 

After a closer look at your screenshot, it looks like it could be an adblock extension that is preventing `sdkloader` from loading, which may be preventing the Twitch SDK from being loaded.

@hellojere this looks like a separate issue where the Vimeo player is attempting to play your MP4 file, as the URL for the file contains `vimeo.com`.

**Comment by hellojere** [comment]
@CookPete Hmmn. Ok. It indeed should be playing an MP4 and not embedding a Vimeo player at all. I'll look into other solutions for this. Cheers.

**Comment by CookPete** [comment]
>already remove adblock and other type of that extension, and the error continues the same.

@pedropcruz What are the exact console errors you are seeing with adblock disabled?

**Comment by nkane** [comment]
I seem to be receiving a similar error without the chat rendering

![image](https://user-images.githubusercontent.com/6445086/50569057-fc0cde00-0d2a-11e9-986d-645d7d3f680e.png)

this is my render call:

![image](https://user-images.githubusercontent.com/6445086/50569065-1a72d980-0d2b-11e9-8786-c18d8aca78bd.png)

even with a src added, it still errors out at a window.appendChild function call.

**Comment by CookPete** [comment]
Just had a closer look – you guys are trying to use options for the [Embed Everything](https://dev.twitch.tv/docs/embed/everything/) player like `chat`, `layout` and `theme`. Currently ReactPlayer uses the [Interactive Frame](https://dev.twitch.tv/docs/embed/video-and-clips/#interactive-frames-for-live-streams-and-vods) player, which uses fewer options.

I'll see if it makes sense to switch over to use `Twitch.Embed()` for everything rather than `Twitch.Player()` – perhaps using `Twitch.Embed()` only if certain options are set.

**Comment by CookPete** [comment]
Turns out that `Twitch.Embed()` doesn't quite work for us as it [only has events for `ready` and `play`](https://dev.twitch.tv/docs/embed/everything/#available-events). I think the solution here is to only embed the video, and [embed the chat window](https://dev.twitch.tv/docs/embed/chat/) separately by following the Twitch docs.
