### ISSUE TITLE
FilePlayer width and height forced to 'auto' or '100%'

### ISSUE THREAD

**Issue by narkowicz** [CookPete/react-player#404]
I'm trying to set `ReactPlayer` (using `FilePlayer`) to a custom `width` / `height` of `n%` using props.

Currently, the `FilePlayer` is setting the style props to `100%` if anything other than `auto` is passed, see relevant lines below:

https://github.com/CookPete/react-player/blob/7364be4555b8cfc18e0d5736e1024a65032dc7c2/src/players/FilePlayer.js#L208-L209

Not sure if this is intentional?

Can try to work around this using containing elements to affect the size but it's not ideal.

**Comment by CookPete** [comment]
This is intentional. The size of the player is determined by the `ReactPlayer` wrapper div using `width` and `height` props passed in to ReactPlayer. The `100%` here is to fill that wrapper, unless `auto` is used, to just render the video at it's native size.

https://github.com/CookPete/react-player/blob/7364be4555b8cfc18e0d5736e1024a65032dc7c2/src/ReactPlayer.js#L107

If you really wanted to override the `style` of the inner `<video>`, you could use `config.file.attributes`: 

```jsx
<ReactPlayer
  url={url}
  config={{
    file: {
      attributes: { 
        style: { width: '50%', height: '50%' }
      }
    }
  }}
/>
```

**Comment by narkowicz** [comment]
Thanks for clarifying so quickly Pete, I'll add another wrapper to make it work.

Cheers.
