### ISSUE TITLE
Window Not Defined

### ISSUE THREAD

**Issue by lecarles** [CookPete/react-player#410]
Error when deploying build w/ Gatsby (static site generator), -> WebpackError: window is not defined.

Looking for a workaround right now (https://www.gatsbyjs.org/docs/debugging-html-builds/#fixing-third-party-modules) but apparently the module can be fixed. 

![captura](https://user-images.githubusercontent.com/35672759/40638156-d172bf46-6309-11e8-86b6-aee088211762.PNG)

**Comment by CookPete** [comment]
I'm not sure ReactPlayer will work as part of a static site. The library heavily relies on the browser environment and 3rd party libraries to play videos. Even if you fixed the problem here (adding `typeof window !== 'undefined'` in the `FilePlayer.canPlay()` logic) I'm still not sure it would work.

That said, I suppose the package is popular enough to warrant making sure it doesn't cause errors when rendering on the server/node (even if it doesn't actually work when compiled).

**Comment by lecarles** [comment]
Forgot to said it - I haven't gotten it to work yet when deploying, but the library works perfectly in local development builds though.

**Comment by nicolasporion** [comment]
@lecarles Hello, I have the same issue, did you found a solution ?

**Comment by lecarles** [comment]
No, not really - I haven't really tried because I've been looking for a an alternative (as @CookPete said that he wasn't sure reactvideo was the most adequate thing to use with a static site). Anyway if you want to fix it you can look at this https://www.gatsbyjs.org/docs/debugging-html-builds/#fixing-third-party-modules or maybe try and implement the solution he said a few comments up.

**Comment by CookPete** [comment]
This should be sorted in `1.6.3`.
