### ISSUE TITLE
Soundcloud player pauses just after song is played

### ISSUE THREAD

**Issue by samuelbriole** [CookPete/react-player#417]
Hi, 

I am using ReactPlayer with Soundcloud, and I control the player with my custom controls.

When I render my ReactPlayer with playing=true, the play event is triggered, and then the pause event is trigger twice just after. 
If I hit pause and play again, the same scenario occurs, and I receive an error from w.soundcloud.com: "Uncaught (in promise) DOMException: The user aborted a request."

The only way to unblock the player is to click on the on the play button on the widget, but this is not ideal as my goal is to use the custom controls only.

**Comment by samuelbriole** [comment]
Quickly looking at the code, I found out that the event SC.Widget.Events.READY is not used to trigger the onReady method. Could it be a problem ?

**Comment by CookPete** [comment]
>When I render my ReactPlayer with playing=true, the play event is triggered, and then the pause event is trigger twice just after.

The Soundcloud widget is pausing because the browser is not allowing it to autoplay (assuming you are using Chrome 66+). I'm not sure why it pauses twice but I don't think it's relevant to the problem.

>The only way to unblock the player is to click on the on the play button on the widget, but this is not ideal as my goal is to use the custom controls only.

You can use custom controls, you just need to keep your `playing` state in line with the widget state. For example, `setState({ playing: false })` when the `onPause` callback is fired.

You can see this working on the [demo page](http://cookpete.com/react-player/). Click `Pause` first before loading a soundcloud track. When loaded, the custom `Play` button will play the track.

>Quickly looking at the code, I found out that the event SC.Widget.Events.READY is not used to trigger the onReady method. Could it be a problem ?

`onReady` is called using the `load()` callback instead of the `READY` event:

https://github.com/CookPete/react-player/blob/7b2784d7d3a4a62b17fa8b46f62a9741e4d97c3d/src/players/SoundCloud.js#L34-L42

**Comment by samuelbriole** [comment]
Thanks for the quick reply

> The Soundcloud widget is pausing because the browser is not allowing it to autoplay (assuming you are using Chrome 66+). I'm not sure why it pauses twice but I don't think it's relevant to the problem.

I just tested on Firefox and the widget is auto-playing correctly ! Safari has the same problem as Chrome. Do you know if there is a workaround ?

**Comment by CookPete** [comment]
>Do you know if there is a workaround ?

If there was then I imagine browsers would just continue to fix the workarounds in later releases. The reality is that blocking autoplay is becoming the norm.

**Comment by samuelbriole** [comment]
OK I see, thanks for the heads up !
