### ISSUE TITLE
Add request headers to the url?

### ISSUE THREAD

**Issue by snly2386** [CookPete/react-player#434]
Can the video support adding request headers (e.g. some sort of authorization for protected videos) to the url property?

**Comment by CookPete** [comment]
Looks like this is not possible. See https://security.stackexchange.com/a/175698.

**Comment by itsalb3rt** [comment]
> I "solved" using fetch
> 
> ```
> try{
>   const result = await fetch(<url>, {
>     headers: {
>       Authorization: "<token>"
>     },
>   });
>   const blob = await result.blob();
>   if(blob){
>     this.setState({ fileName: URL.createObjectURL(blob), playing: true});
>   }
> }catch(err){ }
> ```

This work! no only for react-player, i use this in [react-h5-audio-player](https://github.com/lhz516/react-h5-audio-player).

Thanks

**Comment by Rijon1810** [comment]
try{
  const result = await fetch(<url>, {
    headers: {
      Authorization: "<token>"
    },
  });
  const blob = await result.blob();
  if(blob){
    this.setState({ fileName: URL.createObjectURL(blob), playing: true});
  }
}catch(err){ }



in server it take too much time load. what is the solution?

**Comment by Frikster** [comment]
If you're using django you could use sessions, django signals and nginx and solve this on the backend rather than frontend.

Place in `views.py` that will check for authentication:
```
class GetUserMixin(object):
    def get_user(self, request):
        user_pk = request.session.get(AUTHENTICATION_USER_SESSION_KEY)
        return get_user_model().objects.get(pk=user_pk)
```

Signal, which can be placed anywhere:
```
def user_logged_in_receiver(sender, **kwargs):
    kwargs['request'].session[AUTHENTICATION_USER_SESSION_KEY] = kwargs['user'].pk


user_logged_in.connect(user_logged_in_receiver)
```

make nginx receive the url you put in the player and let it proxy to your endpoint in `views.py` that then uses `get_user` to retrieve the user from your session and thereby huzzah, no more "AnonymousUser" annoyance.

Then the normal thing to do is check `user.is_authenticated` (or whatever other attribute you care about checking for) and add the `'XAccel-Redirect'` header so that nginx will redirect to the protected path that then finally gives the client the video media file segments. See [Protect Django media files per user basis with nginx](https://b0uh.github.io/protect-django-media-files-per-user-basis-with-nginx.html)

**Comment by wparam** [comment]
> I "solved" using fetch
> 
> ```
> try{
>   const result = await fetch(<url>, {
>     headers: {
>       Authorization: "<token>"
>     },
>   });
>   const blob = await result.blob();
>   if(blob){
>     this.setState({ fileName: URL.createObjectURL(blob), playing: true});
>   }
> }catch(err){ }
> ```

It does't work for progressive downloading.

**Comment by ARFayyaz** [comment]
> > I "solved" using fetch
> > ```
> > try{
> >   const result = await fetch(<url>, {
> >     headers: {
> >       Authorization: "<token>"
> >     },
> >   });
> >   const blob = await result.blob();
> >   if(blob){
> >     this.setState({ fileName: URL.createObjectURL(blob), playing: true});
> >   }
> > }catch(err){ }
> > ```
> 
> It does't work for progressive downloading.

Yup, doesnt work for progressive downloading. Any suggestions?

**Comment by Nusab19** [comment]
> Yup, doesnt work for progressive downloading. Any suggestions?

From : https://stackoverflow.com/a/54388012/18256963

The solution I used is to modify the XHR request send by HLS when loading the stream. This is made by giving to ReactPlayer component some options for hls :

```js
<ReactPlayer
config={{
  file: {
    hlsOptions: {
      forceHLS: true,
      debug: false,
      xhrSetup: function(xhr, url) {
        if (needsAuth(url)) {
          xhr.setRequestHeader('Authorization', getToken())
        }
      },
    },
  },
}}
/>
```
The list of options for hls is available [here](https://github.com/video-dev/hls.js/blob/master/docs/API.md#fine-tuning).

You may use this since react-player version 1.1.2 according to [this github issue](https://github.com/CookPete/react-player/issues/325#issuecomment-364035473)

**Comment by zeyadetman** [comment]
Solved it by creating two instances of the `ReactPlayer`, one to get the authorized link and the other one to stream the audio.

```js
const [finalAudioUrl, setFinalAudioUrl] = useState("");

{
  !finalAudioUrl && (
    <ReactPlayer
      url={src}
      config={{
        file: {
          forceHLS: true,
          hlsOptions: {
            xhrSetup: async function (xhr, url) {
              xhr.open("GET", url);
              xhr.setRequestHeader("Authorization", `Bearer ${token}`);
              xhr.addEventListener("progress", function () {
                if (this.responseURL && !finalAudioUrl) {
                  setFinalAudioUrl(this.responseURL);
                  this.abort();
                }
              });
            },
          },
        },
      }}
      style={{ display: "none" }}
    />
  );
}



<ReactPlayer ref={ref} url={finalAudioUrl} />;

```
