### ISSUE TITLE
subtitles do not seem to be working

### ISSUE THREAD

**Issue by nsatija** [CookPete/react-player#443]
The example page also does now have subtitles and having passed a vtt url, just tested that it isnt working :(

**Comment by CookPete** [comment]
Not sure exactly what how you are trying to get subtitles working, but [this jsFiddle](https://jsfiddle.net/1ma6kdrL/) should get you started, based on the example from [here](http://iandevlin.github.io/mdn/video-player-with-captions/). Note the `crossOrigin` attribute because the subtitles are on a different domain.

**Comment by nsatija** [comment]
thanks for the jsfiddle link
