### ISSUE TITLE
In the online demo, pressing play after stop on the mp3 does not resume

### ISSUE THREAD

**Issue by christiaanwesterbeek** [CookPete/react-player#444]
- Visit https://cookpete.com/react-player/
- Click on the mp3
- It plays
- Hit stop
- It stops
- Hit play
- It's not playing...

After pause, play does resume. Is it intended for play not to work after hitting stop?

OS: macOS High Sierra
Browser: Tested both Chrome, Canary build of Chrome and Firefox

**Comment by CookPete** [comment]
Hitting stop simply sets the `url` prop to `null` and unmounts all players. You have to explicitly play a URL after hitting stop otherwise nothing will happen.

Note that this is just a design choice of the demo page, not a definition of what "stop" should mean. Maybe "reset" would be a better label for that button.
