### ISSUE TITLE
Is react player using html5 video or flash??

### ISSUE THREAD

**Issue by zverexe** [CookPete/react-player#447]
I have some issues in some browsers, like FF when video isn't playing until I installed flash. I use react player to loading video from wistia. So is react-player working on html5 video or flash? Is it somehow configurable?

```
import React from 'react';
import ReactPlayer from 'react-player';

import Styles from './styles.scss';

const VideoPlayer = (props) => { 
  return (
    <div className={Styles['video-container']}>
          <ReactPlayer url={props.video}
                       className={Styles.player}                     
                       config={{
                         file: {
                           forceVideo: true,
                         },
                       }}
          />        
    </div>
  );
};

export default VideoPlayer;
```

**Comment by CookPete** [comment]
No flash is used unless the [SDK for a particular URL type](https://github.com/CookPete/react-player#supported-media) uses flash, although I'm pretty sure none of them do. 

Passing in a file URL will just render a simple HTML5 `<video>` player.

If you can recreate the issue in a jsFiddle, that would help me understand what the issue is. Use [this one](https://jsfiddle.net/e6w3rtj1/) as a starting point.

**Comment by zverexe** [comment]
@CookPete thank you
