### ISSUE TITLE
Unavailable This video can't be embedded.

### ISSUE THREAD

**Issue by rostislav-bobrovsky** [CookPete/react-player#464]
Hi @CookPete ,

I'm experiencing a slight problem with `react-player` on some facebook videos. 

If a video cannot be embedded, it causes all the other videos to display the same message. In other words, the [ReactPlayer] fails to work properly and just throws the following message on changing a url, because it will never be loaded: _Player.js:179 ReactPlayer: the attempt to load {video} is being deferred until the player has loaded_  

![aug-13-2018 15-32-27](https://user-images.githubusercontent.com/29147636/44031931-2ec8e8e2-9f0e-11e8-980f-800a7f826d32.gif)

Also, the [ReactPlayer] doesn't throw any errors, so I cannot find a good workaround on that.
In order to avoid this problem, you could pass the `key` prop with, for example, a new video id. It will lead to unmounting and recreation and, therefore, let the problem go away, but it also leads to a slow performance.

The facebook video ID is `2061408887454620`
I'm using `react-player@1.6.4`

Do you have any thoughts on how we can deal with that?

Thank you in advance

**Comment by CookPete** [comment]
The bug is occurring because of [this logic](https://github.com/CookPete/react-player/commit/301aebf7ddf38e09a49bbcae58c1a16edccb1ba5) to prevent [issues when switching quickly between URLs](https://github.com/CookPete/react-player/issues/377).

Annoyingly, Facebook's Video Player API doesn't trigger any events when the video can't be embedded, so we can't set `isLoading` back to `false` when it happens.

I hacky fix for the meantime would be to manually set the flag on the internal `player` instance before loading another URL:

```jsx
class Player extends Component {
  state = {
    url: null
  }
  load (url) {
    if (this.rp.player) {
      this.rp.player.isLoading = false
    }
    this.setState({ url })
  }
  render () {
    return (
      <div>
        <ReactPlayer 
          ref={rp => this.rp = rp}
          url={this.state.url}
        />
        <button onClick={() => this.load(EMBEDDABLE_URL)} />
        <button onClick={() => this.load(NON_EMBEDDABLE_URL)} />
      </div>
    )
  }
}
```

**Comment by CookPete** [comment]
Hopefully this is fixed in `1.6.5`

**Comment by ishantmehta01** [comment]
I am using this URL, which says "This video can't be embedded because it may contain content owned by someone else."
URL: https://www.facebook.com/LaMonnaieDeMunt/videos/270512041924875/?ref=embed_video

I can open this Video in incognito mode

https://cookpete.github.io/react-player/

<img width="1722" alt="Screenshot 2024-07-30 at 3 30 24 PM" src="https://github.com/user-attachments/assets/b5b6ff45-49c3-4edb-96aa-4af2e6bf6793">

@cookpete Could you help here?

**Comment by starkkumarkk1611** [comment]
Hey I am facing the same issue isn't there any way to know is video is played or not so that I can trigger some state changes according to that
