### ISSUE TITLE
Looped YouTube video doesn't call onEnded when looped

### ISSUE THREAD

**Issue by bradywestveer** [CookPete/react-player#471]
If you have the loop option in the context menu (right-click the player) of a YouTube video on, the video loops and does not call onEnded on the player component. How can I get onEnded to be called each time the video loops?

**Comment by superbuggy** [comment]
Could you use the `onDuration` and `onProgress` callbacks?

**Comment by bradywestveer** [comment]
`onDuration` is only called once per looped video. `onProgress` returns zero twice, so I could listen for two zeroes, but I feel like there is/should be a better way to solve this.

**Comment by CookPete** [comment]
It's annoying but technically this is correct behaviour. There are a few things going on here:

- The YT iframe API doesn't actually set `loop` correctly when you pass in `loop: 1` to the `playerVars` config object. You can still right click the video and see that `Loop` is unchecked.
- Because of this, ReactPlayer listens for the YT player's state to change to `ENDED` and then [manually restarts the video](https://github.com/CookPete/react-player/blob/master/src/Player.js#L172-L174).
- If you manually set the video to loop via the context menu. YouTube won't change the player state to `ENDED`, because now the player _knows_ that you want to loop the video, the video doesn't technically ever "end".
- It doesn't look like there are any API events or player states relating to when a video loops.

If for some reason you still want to detect when a video loops, even after manually setting Loop to true, you could store the duration from `onDuration` and then listen for changes to `playedSeconds` from the end of the video (when `duration - playedSeconds` is less than 1, or 2 or 3) to the start of the video (`playedSeconds` between 0 and 1).
