### ISSUE TITLE
How to loading HLS file?

### ISSUE THREAD

**Issue by YuK1Game** [CookPete/react-player#478]
```
<ReactPlayer url={'http://example.com/test.m3u8'} />
```

are not working.

I confirmed this URL on the iPhone.

**Comment by CookPete** [comment]
It's impossible to know what the problem is without more information. What URL are you trying to play? Do you get any console errors or callbacks from the `onError` prop? The example HLS stream works in browsers as well as iOS, so I'm assuming it must be something specific to your stream. Feel free to reopen with more information.
