### ISSUE TITLE
Question/Help

### ISSUE THREAD

**Issue by davidrenne** [CookPete/react-player#501]
I implemented it and things are looking good in my tests, but whenever I open up full screen on my implementation I see this error seems to be caught with my window.error handler but not logged in my console.

`Client Side Error: ResizeObserver loop limit exceeded`

Keep in mind I am embedding this inside a hint popup:

https://github.com/slmgc/react-hint

I also had a resize event handler in the page and I took it out and the error is still showing up after I get out of full screen.

So my quick and dirty question, is there a prop or some way that I can disable the full screen from the canned controls using the control={true} prop?

**Comment by davidrenne** [comment]
Seemed to have fixed itself magically.  Maybe something else was happening

**Comment by sergio-bravo** [comment]
No it didn't, the error is caused by chromium bug:
https://stackoverflow.com/questions/49384120/resizeobserver-loop-limit-exceeded

Affected browser:
Chrome: 63.0.3239 (ResizeObserver loop limit exceeded)
Chrome: 64.0.3282 (ResizeObserver loop limit exceeded)
Edge: 14.14393 (SecurityError)
Edge: 15.15063 (SecurityError)

The severity is low, but it can be prevented completely with requestAmimationFrame

**Comment by davidrenne** [comment]
Nice find!
