### ISSUE TITLE
Pausing video does not clear the onProgress timeOut

### ISSUE THREAD

**Issue by vermiliongrey** [CookPete/react-player#51]
Mostly a visual issue, but when pausing the video, there will often be another "tick" of the seek bar since the onProgress timeOut isn't cleared.

**Comment by CookPete** [comment]
The timeout is deliberately not cleared, because we might still want to get updates to the `loaded` percentage even when paused. Perhaps two progress callback props are needed instead, like `playProgress` and `loadProgress`.

Or, an easier fix would be just to check for `this.props.playing` [here](https://github.com/CookPete/react-player/blob/f0d2ffbf73702b7ae755a031efcdf4b692cf3a8a/src/ReactPlayer.js#L44), which would just not include the `played` property if the media is paused.
