### ISSUE TITLE
I have to double tap on mobile (iOS)

### ISSUE THREAD

**Issue by wdaneiliff** [CookPete/react-player#543]
Hey,

I'm using React-Player on my website to play songs from soundcloud and youtube.  On desktop the player works amazing. 

However, on mobile (iOS) the first time I press the play button for a song it works but then when I go to press play for another song - it requires me to press it twice.  

Is there any way to get past this issue? 

Here is a link to my site:   http://rockwiththis-staging.com

Here is the code for my player: 
<img width="1023" alt="screen shot 2018-12-24 at 5 04 43 pm" src="https://user-images.githubusercontent.com/12902568/50408381-36f89a00-079e-11e9-9e9d-64338fc75466.png">

**Comment by ShakurOo** [comment]
Same here

**Comment by charlesbdudley** [comment]
I've noticed that when the Player is rendered every element on the page requires a double tap on iOS safari. Seems intermittent unfortunately.

**Comment by CookPete** [comment]
It sounds like each player simply needs user interaction, which is a common problem with media on iOS. I don't know if there's anything this library can do about this.

>I've noticed that when the Player is rendered every element on the page requires a double tap on iOS safari. Seems intermittent unfortunately.

Every element on the page? This stinks of a problem with the iOS browser rather than the library.

Unfortunately I don't know what can be done about this so I'll close it off for now. If anyone can reduce this down to a specific thing that ReactPlayer is doing wrong, feel free to reopen with more details.
