### ISSUE TITLE
Native Resolution

### ISSUE THREAD

**Issue by jjarrett21** [CookPete/react-player#622]
Is there any easy way to get the native resolution from the loaded video?

**Comment by CookPete** [comment]
Please do not ignore the issue template, even for things that aren't bugs. Your issue is hard to solve without knowing more information. What type of video are you trying to play?

Assuming you are playing a file, [this post](https://stackoverflow.com/questions/4129102/html5-video-dimensions) says you can check `videoWidth` and `videoHeight` on the video element. Use the `getInternalPlayer()` instance method to access the video element.

Example: https://jsfiddle.net/qw7agy4p/

**Comment by jjarrett21** [comment]
Thank you, if I have any further questions I'll be sure to follow the template.

**Comment by nwaxiomatic** [comment]
This does not work for Vimeo as of 2022
