### ISSUE TITLE
Light property not working with FilePlayer

### ISSUE THREAD

**Issue by pcegarra** [CookPete/react-player#636]
Using FilePlayer the light image url does not appear, but using ReactPlayer yes

**Comment by oxorp** [comment]
Stumbled upn the same Error today using local files as url prop. 

```<div className=" card-img-top img-fluid player-wrapper">
      <ReactPlayer
        className="react-player-custom"
        width={'100%'}
        height={'100%'}
        controls
        loop={false}
        url={VIDEO_DIR + video.name + VIDEO_EXT}
        light
      />
 ```
leads to `Uncaught (in promise) SyntaxError: Unexpected token U in JSON at position 56
    at C:\Users\proxo\Documents\Code\hochlicht\node_modules\react-player\lib\Preview.js:156`

noembed response looks like this:
```{
  "error": "no matching providers found",
  "url": "C:Usersproxo/Documents/Overwatch/videos/overwatch/afe.mp4"
}
```

**Comment by CookPete** [comment]
@pcegarra The logic for `light` mode lives in the top level `ReactPlayer` component, and not in the individual imported players. You’ll have to use `ReactPlayer` if you want to use `light` mode.

@oxorp That makes sense. If you're playing a local file and using `light` mode, you need to pass in a poster image URL to the `light` prop, otherwise `noembed` obviously won't know anything about your local file URL.
