### ISSUE TITLE
Local file playing start from != 0

### ISSUE THREAD

**Issue by wuahi** [CookPete/react-player#669]
#### Current Behavior
There is no way to set local video start point (in seconds) like with youtube videos.

#### Expected Behavior
Have it the same way as with youtube streams, i.e: 
`{...
 start: <start_position_in_seconds>
}
`

#### Steps to Reproduce
1. Set local file url for videoplayer
2. Try to seek before video starts playing
3. Video resets to zero

#### Environment
- URL attempting to play: local
- Browser: Chromium
- Operating system: Ubuntu linux

**Comment by CookPete** [comment]
`start` only works for YouTube videos because it's supported by the player params that can be passed in. There is no equivalent for HTML5 video, so no way to support the same thing.

You could wait for `onReady` and then use `seekTo` to immediately seek to a certain time and start playing, but this is not an ideal solution, and so isn't baked in to `ReactPlayer`.
