### ISSUE TITLE
[Vimeo player] playback fails when swapping URLs too quickly

### ISSUE THREAD

**Issue by panzerstadt** [CookPete/react-player#683]
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

#### Current Behavior
whe switching between urls too quickly, Vimeo player fails to load and stays black

#### Expected Behavior
vimeo player should play when urls change, or failure to load player should recover on next url load

#### Steps to Reproduce
1. go to https://cookpete.com/react-player/
2. click on Test A under Vimeo
3. wait for it to play
4. click on Test B for Vimeo and then quickly click on Test A again
5. player stops playing, shows a black screen
6. error is thrown in console: Player.js:41 ReactPlayer: the attempt to load https://vimeo.com/xxxxxxxxx is being deferred until the player has loaded
7. further changes in vimeo urls are unable to resolve the problem

#### Other Information
does not seem to be an issue with other players (from the initial test on the website)

**Comment by CookPete** [comment]
I think this is due to [this line](https://github.com/CookPete/react-player/blob/ad5d6df62635497137a184cf93a9c43ba6b08fbb/src/players/Vimeo.js#L116) of the Vimeo player which will kill any player mid-load if a new `url` arrives. The original video never gets a chance to `onReady` or `onPlay` and so the `loadOnReady` logic never kicks in.
