### ISSUE TITLE
save/playblack feature on video steaming

### ISSUE THREAD

**Issue by broros** [CookPete/react-player#715]
playback/saving of videos that are streaming, is this possible?

**Comment by jhodges10** [comment]
I think it's pretty far to say that functionality is outside the scope of this player library.

If you want to add a download button for YouTube / Vimeo that's definitely not going to happen, because they make that pretty difficult. And if you're displaying an HTML5 video, then the built-in controls generally provide that option out of the box.

**Comment by CookPete** [comment]
Yeah @jhodges10 pretty much nailed it. This also was an extremely vague, unhelpful issue.
