### ISSUE TITLE
Handlers use stale variables from the upper scope

### ISSUE THREAD

**Issue by good-idea** [CookPete/react-player#725]
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

#### Current Behavior

Handlers like `onProgress` use stale variables. Any reference to variables from the upper scope within a handler (such as state, or updated props passed into the component) uses whatever that value was at the time the handler was created.

(I believe this is the same as https://github.com/CookPete/react-player/issues/511)

#### Expected Behavior
Handlers should have access to up-to-date props and state as normal

#### Steps to Reproduce
See example: https://codesandbox.io/s/wild-snowflake-uv5wj

The `time` state is incremented by 1 every second.
The `onProgress` handler always logs `time` as 0
The `onClick` handler assigned to the button logs the proper `time`

**Comment by CookPete** [comment]
This happens due to this line of the `isEqual` util, which is used in `shouldComponentUpdate`:
https://github.com/CookPete/react-player/blob/1e41ce5ce5e2d6946701723f60e74326385df92d/src/utils.js#L150-L152

By default, we don't want to needlessly re-render ReactPlayer every second. The caveat of this is that if no props change, the first function passed in will always be the one called.

I'm not sure what can be done.. perhaps an extra prop should be added to force ReactPlayer to always re-render? 

In the meantime, this can be fixed by passing in a dummy prop that will always change, like `data-cache={time}` in your example, which will re-render the component and use the latest `onProgress` passed in.
