### ISSUE TITLE
Fullscreen callback toggle.

### ISSUE THREAD

**Issue by MirceaMuraru** [CookPete/react-player#744]
Hello, I currently have an issue with the fullscreen callback. If I use the player without controls and use the fullscreen callback function from documentation, it works, but when I click the "fullscreen" icon, it toggles, but it remains on fullscreen.

I also reproduced this within the demo from documentation.

**Comment by CookPete** [comment]
What fullscreen callback are you referring to? All the fullscreen behaviour is dealt with by [screenfull](https://github.com/sindresorhus/screenfull.js/), and not really related to ReactPlayer.

My guess is that you're using `screenfull` to put the ReactPlayer wrapper element in fullscreen mode, then toggling the native fullscreen button, which attempts a different type of fullscreen (and does nothing because you're already in fullscreen mode).

**Comment by MirceaMuraru** [comment]
First of all thank you for you prompt answer, how can I toggle players fullscreen method?

**Comment by CookPete** [comment]
It depends what URL you are playing. Mixing `screenfull` and the native player fullscreen is always going to cause problems. If the player API supports a fullscreen method, then you might be able to call that from outside the player. If not, there is not much we can do.
