### ISSUE TITLE
YouTube. SeekTo without starting the playing does not change the image

### ISSUE THREAD

**Issue by nilecrocodile** [CookPete/react-player#755]
Hello! I have a problem. I need to rewind the video to the desired time stamp when loading the player. To do this, I use the "seekTo" method. But after that the picture of the video does not change. To make the picture relevant, I do an unpleasant trick: I call "playVideo" and then the next calling of the "onBufferEnd" callback function, I call the "pauseVideo" function. This leads to the fact that the video sometimes jerks quickly, and heard the twitch.

Tell me how to correctly put the video on the right time stamp immediately after downloading so that the picture corresponds to the point in time.

**Comment by CookPete** [comment]
As far as I'm aware, seeking a Youtube player won't work until it has started playing at least once, so I'm not sure there is a way to achieve this without the flicker that you mention. You could use `onStart` rather than `onBufferEnd` but you still have a strange flicker: https://jsfiddle.net/xkhb14Lq/

This method also seems to show the stupid "related videos" popup and apparently these [cannot be turned off](https://stackoverflow.com/a/52890021)...
