### ISSUE TITLE
bug on the Safari and Chrome on iOS 13.2.2 devices with seekTo on YouTube player

### ISSUE THREAD

**Issue by nilecrocodile** [CookPete/react-player#756]
The essence of the bug.

An incorrect value comes to a callback function _onProgress_ once after calling the "_seekTo_" function.

Example:
_onProgress_ gets the values ​​`{playedSeconds} ` (values for example):
1.01 initial
2.02 higher
3.03 higher
4.04 higher
5.05 higher
... and so on

Then on the timestamp "5.05" we call "_seekTo_" to the label "2.00".
After that the function _onProgress_ will receive the following values:
5.06 <- apparently the last challenge of progress
2.00 <- correct
**1.98** <- **LESS - INCORRECT VALUE (this is bug)**
2.01 <- higher
2.02 <- higher
...then everything is right

On version iOS 12.4 there is no bug. Also it is not on Android devices and desktop browsers, including desktop Safari on macOS.

**Comment by CookPete** [comment]
I think this is just an unfortunate nuance in the way that Youtube seeking and `getCurrentTime` works, together with the fact that `onProgress` is called every second, but not _exactly_ every second (because of drift) and not exactly in time with any calls to `seekTo` or  `getCurrentTime`.

My guess is that after calling `seekTo` on these certain browsers, Youtube will sort of _snap_ the seeking position to the nearest keyframe or certain point. In your case, this happens to be `1.98` seconds. I'm not sure what this library can do about this.
