### ISSUE TITLE
onReady prop called multiple times with files as url

### ISSUE THREAD

**Issue by ericxinui** [CookPete/react-player#760]
Be sure to [search for your issue](https://github.com/CookPete/react-player/issues) before opening a new one.

#### Current Behavior

When using the component to play a file, onReady prop is called infinitely. 

#### Expected Behavior

onReady prop called only once

#### Steps to Reproduce

1. Use <ReacPlayer> with a file as url 
2. Put some function in onReady prop (I used a console.log)

#### Environment
- URL attempting to play: file stored in Google storage (local file too produce presented bug)
- Browser: Google Chrome Version 78.0.3904.97 (Official Build) (64-bit)
- Operating system: Ubuntu 16.04.5 LTS
- jsFiddle example:

**Comment by CookPete** [comment]
The `onReady` event listens to the `canplay` event for files. If this is a weird OS/browser quirk or something specific to the type of file, I don't know what this library can do about this.

Feel free to reopen this issue with an example jsFiddle or detailed steps to reproduce.

**Comment by LevanKantaria** [comment]
I faced the same problem when using any source other that Youtube ( I am using playerRef.current.seekTo( ... ) function and this was causing onReady event to loop, this problem does not exsit when using YT links ).  I decided to keep state of isReady separately and attach my logic to that state instead of listening to onReady. Not sure if this is a good fix, but works for me
