### ISSUE TITLE
Setstate in onReady prop - unexpected behaviour

### ISSUE THREAD

**Issue by seand52** [CookPete/react-player#763]
**Current Behavior:**
I have a component that has a _videoLoaded_ state set to false initially.
In the onReady prop I have a setState that changes the videoLoaded state to true. 

The problem I am having is that when I have this setup the video takes more than 10-15 seconds to load However, when I remove all this logic it loads instantly. 

I have tested this behaviour in different browsers and it seems like it happens consistently in Firefox, but also happened in Chrome a few times.

Am I using the onReady prop correctly? Is this a bug?

**Expected Behavior**
I would expect the state of videoLoaded to change when the video is ready so I can stop displaying the loader and show the video.

**Environment**
- Browser: Firefox/Chrome
- Operating system: MacOS

**Comment by CookPete** [comment]
You're probably going to have problems if you aren't displaying the video during loading (due to the way most of the external APIs work).

I would suggest something like `position: absolute; opacity: 0.01;` to fool the browser into thinking the video is still showing. Give it a go and reopen this issue if you still have trouble, preferably with an example jsFiddle or more detailed steps to reproduce the problem.
