### ISSUE TITLE
dynamically changing url, using object url 

### ISSUE THREAD

**Issue by kdog1425** [CookPete/react-player#77]
I'm trying to let the user choose an mp4 file from the local file system. 
and then I use 
`URL.createObjectURL(file)`
to make that file into a blob url.

My debugging shows that the blob url is created and playable, and reaches the react component as expected (I've also tested with html5 <video> tag to make sure), and the react component is re-rendered. 

However, when using 'react-player', it seems the video does not load with this approach.

**Comment by kdog1425** [comment]
I suppose this approach is not possible since react-player uses youtube player under the hood, which I am not sure is able to play 'blob:' urls.

**Comment by CookPete** [comment]
>I suppose this approach is not possible since react-player uses youtube player under the hood

ReactPlayer uses the youtube player only when passed a youtube URL. It uses a simple `<video>` or `<audio>` tag when passed a file URL. I had never considered using blob URLs, if they work as a source of `<audio>` or `<video>` tags then adding support would be as easy as updating the [file matching regex](https://github.com/CookPete/react-player/blob/master/src/players/FilePlayer.js#L5-L6) so that `FilePlayer` is used for those URL patterns.
