### ISSUE TITLE
Playbackspeed for Twitch doesn't work

### ISSUE THREAD

**Issue by johnyoonh** [CookPete/react-player#782]
#### Current Behavior
Changing playback speed doesn't affect the playback speed

#### Expected Behavior
Changing playback speed should change the playback speed

#### Steps to Reproduce
On:https://cookpete.com/react-player/
Load a twitch video and press different playbackspeed.
triggering:
  handleSetPlaybackRate = e => {
    this.setState({ playbackRate: parseFloat(e.target.value) })
  }
seems to get ignored by the player

#### Environment
- URL attempting to play: https://www.twitch.tv/videos/534641776
- Browser: Google Chrome
- Operating system: Windows

**Comment by CookPete** [comment]
> playbackRate | Set the playback rate of the player  ◦  Only supported by YouTube, Wistia, and file paths

https://github.com/CookPete/react-player#props

**Comment by johnyoonh** [comment]
@CookPete Would you be able to give me a hint why twitch doesn't work?

**Comment by CookPete** [comment]
>Would you be able to give me a hint why twitch doesn't work?

Because the Twitch interactive player API has no `playbackRate` methods to hook in to:

https://dev.twitch.tv/docs/embed/video-and-clips#interactive-frames-for-live-streams-and-vods

The chrome extension works because (I assume) it just looks for all `<video>` elements (even within iframes) and sets the [`playbackRate`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/playbackRate) property. If we were able to do that we could add support for it, but afaik it's not possible from where ReactPlayer sits.
