### ISSUE TITLE
Bug: canPlay is returning true for all facebook URLs

### ISSUE THREAD

**Issue by sapkra** [CookPete/react-player#793]
#### Current Behavior
After the new update the `canPlay` function is returning `true` for all facebook URLs because of the new matcher. This results in a lot of false positives.

#### Expected Behavior
`canPlay` should only return `true` if it actually can be played.

**Comment by CookPete** [comment]
If anyone can find or create a regex pattern that matches all playable facebook URLs (and solves https://github.com/CookPete/react-player/issues/778) I'll be happy to use it.

**Comment by paulincai** [comment]
@sapkra @CookPete let's start with this. @sapkra are you aware of any url formats that don't work with it?

```javascript
 const url = ..................
 const matchFacebookUrl = /facebook\.com\/([^/?].+\/)?video(s|\.php)[/?].*$/
 const isFBVideo = matchFacebookUrl.test(url)
 console.log(isFBVideo)
```

**Comment by CookPete** [comment]
@paulincai That pattern doesn't match the URL in #778

I'm tempted by this:

```regex
^https?://www\.facebook\.com.*/(video|watch).+$
```

Which just matches any `facebook.com` url that contains `/watch` or `/video` somewhere in it. Quite terse but still covers most use cases:

https://regex101.com/r/VW2BBg/2

**Comment by sapkra** [comment]
@CookPete  I've improved it a bit to not match any facebook pages which include `watch` or `video`.

https://regexr.com/4tdur

**Comment by paulincai** [comment]
@CookPete I get it.

Not related to the present issue/task, the thing is that I use a scrapper for all web content that lands in my platform and the URL in #778, "https://www.facebook.com/watch/?v=499831560618548" ends up as "https://www.facebook.com/francknicolasofficiel/videos/499831560618548/"
This is the "real" URL that ReactPlayer actually plays because the FB SDK returns this URL not the "watch" url.

And now I remember that I decided to rely on the scrapper for consistency of all URLs having them correctly formatted before saving to DB.

I am for @sapkra 's regex. I think it covers well.

**Comment by CookPete** [comment]
Nice one @sapkra. Updated and published in `react-player@1.15.1`. Cheers all for the help.

**Comment by paulincai** [comment]
ok, here's another one, at least for the reference. There is a video URL format which re-re-directs in Facebook.

This is a video content: https://www.facebook.com/story.php?story_fbid=10156618238668888&id=9328458887

the video URL is https://www.facebook.com/adidasoriginals/videos/10156618238668888/

**Comment by sapkra** [comment]
@paulincai Updated the regex in my link to also match this one if necessary.

**Comment by CookPete** [comment]
Updated regex in `react-player@1.15.2`
