### ISSUE TITLE
Player starts again when seeking to the end

### ISSUE THREAD

**Issue by MarcLopezAvila** [CookPete/react-player#816]
Hi,

There is an issue that when the user makes a seekTo dragging the progress bar to the end of the media being played, the media starts again since the beginning. 

We have looked for the bug but we have realized that it happens in the **Demo page it happens too:** https://cookpete.com/react-player/

**Steps to reproduce:**

- Select mp4 file
- Drag the seekBar beyond the end of it
- Release it

The video will start again from the beginning.

**Expected behaviour**

- The video stops playing and the seek is positioned on the end of the media.

Note: It happens too when the player is playing and then executing player.seekTo('end of the media').

Can this be fixed? Thanks!

**Comment by CookPete** [comment]
This is due to this line of `Player.js`:

https://github.com/CookPete/react-player/blob/9be7a9c9d24d08801b1f31f93bdfabf45ea1bf83/src/Player.js#L138

Any seeker that ranges from `0` to `1` will have this problem. Seeking to the very end will `seekTo(1)` and be interpreted as "seek to 1 second" rather than "seek to 100% of the duration".

Two possible solutions:
- Set `max={0.9999999}` on your slider so it never seeks to 1 (not very elegant)
- In your slider logic, use `seekTo(x, 'fraction')` to ensure a fraction is assumed (a bit more elegant)

**Comment by jsbmg** [comment]
Hi, I'm still experiencing this issue, even though I'm using the seekTo(x, 'fraction') format. 

In my case, I have a seek forward by 15 seconds button. If the time to seek to is longer than the duration of the audio, I call `seekTo(1.0, 'fraction')`. But this seems to restart the audio from the beginning. But if I set it to `seekTo(.99, 'fraction')`, it doesn't restart playing the audio from the beginning, but instead of playing from the beginning when the user hits play again, it finished the audio and stops playing, and then you have to press play again to restart playing from the beginning.

I have `loop={false}` and if the audio finishes 'naturally', without seeking to the end, things work as expected.

I also have `playing={false}` when this event occurs, but this prop is ignored, `onPlay` gets called, and it keeps playing.
