### ISSUE TITLE
What is the reason for the isEqual function ignoring functions?

### ISSUE THREAD

**Issue by miracle2k** [CookPete/react-player#857]
Apologies for not using the issue template - I am actually running a fork of the library, so this might not be perfectly applicable anyway, and is more a general feedback note / question than a bug report.

I am passing a custom onClick handler to the `FilePlayer`. This caused issues, because an old version of the handler kept being called. This is because the component does not update if I give a new `onClick` handler, as those kinds of changes are ignored in `isEqual`.

With hooks this is actually more likely to happen, as it is more common for those kinds of callback functions to change identity.

Is there a good reason for doing this, or is it only a convenience thing trying to work around that flaw in React which requires you to bind/memoize functions? Because if the latter, I personally don't think this convenience is worth breaking precedent with the rest of the React ecosystem.

**Comment by miracle2k** [comment]
Even with `isEqual` changed my `onClick` handler was still not passed through to the `FilePlayer` in the most recent version. This was because of this line here:

https://github.com/CookPete/react-player/blob/bb69b1df1972ca50feb97090c8ff35aab5203b3c/src/ReactPlayer.js#L63

Copying `props.config` to `this.config` in `componentDidUpdate`, and rendering with the current value of `this.config` means that if `props.config` changes, the player will not re-render with those changes. They will only be applied on the *next re-render*.

**Comment by CookPete** [comment]
>Is there a good reason for doing this, or is it only a convenience thing trying to work around that flaw in React which requires you to bind/memoize functions?

`isEqual` skipping functions is an [attempt at an optimisation from a while ago](https://github.com/CookPete/react-player/commit/a73a3c8d03a7d2e218e9e892019cc8cb284e223c) to prevent ReactPlayer from re-rendering too often when apps update their state often (eg if they have a current time increasing every second). If people pass in arrow functions to callbacks, it seems wasteful to constantly re-render when nothing is actually changing.

I’m open to suggestions for a better way to avoid too many re-renders. Should we just start comparing functions? Use a better `isEqual` library? Remove the `shouldComponentUpdate` altogether?

>Copying props.config to this.config in componentDidUpdate, and rendering with the current value of this.config means that if props.config changes, the player will not re-render with those changes. They will only be applied on the next re-render.

This came up in #851 and has been fixed in v2.0, which I am hoping to release very soon.

**Comment by miracle2k** [comment]
I don't think there is a good option except to put the onus on the user of the library to memoize their callback functions (using `useCallback` when using books, or `bind` when using class components) if they want the added performance.

Otherwise, if this kind of check exists, I am assuming it is not possible to ever change the "onPlay" callback passed in, and in particular when using hooks, as I said, I would expect this to happen frequently. 

However, because I am using a fork of the library (+ the `getConfig` issue caused me some misdirection as well) it might be worth it to confirm that changing the callback is indeed a problem.

**Comment by CookPete** [comment]
Just published `v2.0.0` which uses `react-fast-compare` for the `isEqual` logic 👍
