### ISSUE TITLE
Twitch videos don't work "Cannot read property 'Player' of undefined"

### ISSUE THREAD

**Issue by lfzawacki** [CookPete/react-player#921]
#### Current Behavior

Using version 2.2.0. Videos from Twitch won't play, the following error is printed on the web console:

`Uncaught (in promise) TypeError: Cannot read property 'Player' of undefined`

The Twitch api file (https://player.twitch.tv/js/embed/v1.js) seems to have loaded correctly.

#### Expected Behavior

Twitch videos should play normally

#### Steps to Reproduce

1. Trying to load any Twitch video url will yield this error.

I've got this application which is integrating with react-player 2.2.0

1. Go to https://paulo.dev.mconf.com/demo/demoHTML5.jsp?username=lfz&isModerator=true&action=create
1. Click the '+' button on the left and 'Share an External Video'
1. Paste a Twitch video (or livestream) link and click 'Share'
1. The video 

#### Environment

- URL attempting to play: https://www.twitch.tv/videos/632091318
- Browser: Chrome 83
- Operating system: Ubuntu 18.04

**Comment by CookPete** [comment]
You have `exports` set in your global scope, which is confusing the Twitch API and setting `exports.Twitch` rather than `window.Twitch`

Normally I would say this isn't ReactPlayer's responsibility to fix, but this is a common problem (https://github.com/CookPete/react-player/issues/846 https://github.com/CookPete/react-player/issues/762 https://github.com/CookPete/react-player/issues/690) and should be quite easy to fix if we just look inside `exports` as well as `window` in the `getSDK` logic.
