### ISSUE TITLE
onProgress stops getting called if playing is set to false

### ISSUE THREAD

**Issue by sniepoort** [CookPete/react-player#94]
I want to start playing the video (a local .mp4) when the loading state reaches a certain level, let's say 0.5.
However, when the playing parameter is set to false, onProgress only get's called initially, and then stops getting called. Am I misunderstanding the concept of onProgress? Shouldn't the video continue being loaded, even if the media isn't playing? I can see in the demo that when the video is paused, loading doesn't take place. Is there any way to achieve what I want then, or is it a browser specific thing?

**Comment by CookPete** [comment]
It's true that `onProgress` stops being called when `playing` is `false`. However, it's also true that `onProgress` is not called when the `played` or `loaded` amounts do not change. It is up to the browser how much of a file they load as they play, and even though [`preload` is set to `auto`](https://developer.mozilla.org/en/docs/Web/HTML/Element/video#attr-preload) in the HTML element, modern browsers are very good at only downloading what they need to play.

If you are attempting to wait until the browser can play the entire media, there is a [`canplaythrough`](https://developer.mozilla.org/en-US/docs/Web/Events/canplaythrough) event that we could perhaps add a prop for, but I'm not sure how consistently this event is fired across different browsers.

**Comment by sniepoort** [comment]
Thanks, that's more or less what I figured was going on. 
I'm not sure about canplaythrough. A quick search says that it should be a more or less reliable event across browsers, although when they fire it seems to be a bit inconsistent. It's up to you if that's a prop you'd like to add. I know i'd like to try it!

**Comment by jmp909** [comment]
Hi @CookPete 

would you be able to make that canplaythrough optional somehow? (ie we can choose to listen for it or not.... in fact all of those events really). 

That event was absolutely critical for a (non-react) video I did for a banner, in order to load enough for the video to (attempt to) play through without buffering. Tested on throttled connection in chrome and it worked great. So having access to it would be very useful.

regards
J

**Comment by CookPete** [comment]
@jmp909 This is actually already possible by passing `attributes` into the `fileConfig` prop, like so:

```js
<ReactPlayer
  url={file.mp3}
  playing
  fileConfig={{
    attributes: {
      onCanPlayThrough: () => console.log('Now I can play it through')
    }
  }}
/>
```

In fact, any other [media event](https://developer.mozilla.org/en/docs/Web/Guide/Events/Media_events) is supported in this way, with the `on` prefix and camelcased to keep React happy.

**Comment by belohlavek** [comment]
Is there any way to track how much the video has loaded **while it is paused**?
onBuffer gets triggered, but I can't find a way to get the exact buffer value while not progressing!

**Comment by CookPete** [comment]
@belohlavek The `onProgress` event doesn't fire whilst paused due to [this commit](https://github.com/CookPete/react-player/commit/180039b19b3975e7e0ecae1202ccb304d829fba7) which was an attempt to fix [this issue](https://github.com/CookPete/react-player/issues/51). There is probably a better solution that allows `loaded` amounts to still be reported whilst paused, so I'll look into it.

It may even be worth splitting `onProgress` into `onPlayedProgress` and `onLoadedProgress` or something to keep things cleaner. Maybe something for `v1.0`.

**Comment by priyathamkat** [comment]
@CookPete `onProgress` is not being called every `progressFrequency` milliseconds in my app, it's only being called once after what seems to `progressFrequency` milliseconds. Are you sure that this shouldn't be
`_this.progressTimeout = setInterval(_this.progress, _this.props.progressFrequency);`
instead of
`_this.progressTimeout = setTimeout(_this.progress, _this.props.progressFrequency);`?

**Comment by CookPete** [comment]
Hey @priyathamkat yeah there seems to be a bug in the most recent version which I will look into. Good spot.

It doesn't need to be `setInterval` because `setTimeout` is being repeatedly set every time `this.progress` is called, which is a better technique for [various reasons](http://thecodeship.com/web-development/alternative-to-javascript-evil-setinterval/).
